import { AlertTriangle, ArrowRight, CheckCircle2, Download, FileSpreadsheet, LockKeyhole, Mail, ShieldCheck } from 'lucide-react';
import { FormEvent, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { Card, Pill, PrimaryButton, SecondaryButton } from '../../components/Primitives';
import { useAgencyStore } from '../../store/AgencyStore';
import { useDistributionStore, type DeliveryMethod, type DistributionRecord } from '../../store/DistributionStore';
import { usePortfolioStore } from '../../store/PortfolioStore';
const input='w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-100';
export default function DistributePortfolio(){
 const {active}=usePortfolioStore(); const {agencies,currentEmployee}=useAgencyStore(); const {createDistribution,markDelivered,alreadySent,activeFileLocked}=useDistributionStore();
 const owned=agencies.filter(a=>a.ownerEmployeeId===currentEmployee.id&&a.contacts.length);
 const [agencyId,setAgencyId]=useState(owned[0]?.id||''); const agency=owned.find(a=>a.id===agencyId); const [contactId,setContactId]=useState(agency?.contacts[0]?.id||'');
 const [method,setMethod]=useState<DeliveryMethod>('email'); const [notice,setNotice]=useState(''); const [prepared,setPrepared]=useState<DistributionRecord|null>(null);
 const prior=useMemo(()=>active&&agencyId&&contactId?alreadySent(active.id,agencyId,contactId):[],[active,agencyId,contactId,alreadySent]);
 function changeAgency(id:string){setAgencyId(id);setContactId(owned.find(a=>a.id===id)?.contacts[0]?.id||'')}
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const r=createDistribution({agencyId,contactId,method,reason:String(f.get('reason')),followUpAt:String(f.get('followUp'))});setNotice(r.message);if(r.record)setPrepared(r.record)}
 function deliver(){if(!prepared||!active?.file)return;markDelivered(prepared.id);if(prepared.method==='download'){if(active.file.dataUrl){const a=document.createElement('a');a.href=active.file.dataUrl;a.download=active.file.name;a.click()}else{const blob=new Blob(['AccountNumber,ConsumerName,Balance\nMASKED-001,REDACTED,1250.00'],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=active.file.name;a.click();URL.revokeObjectURL(a.href)}}setPrepared({...prepared,status:prepared.method==='email'?'sent':'downloaded',deliveredAt:new Date().toISOString()})}
 if(!active)return <Empty title="No active portfolio" body="The owner must activate a portfolio before samples can be distributed."/>;
 return <div className="mx-auto max-w-[1180px] p-5 md:p-8 lg:p-10"><header className="mb-8"><p className="text-sm font-semibold text-blue-600">Distribution engine</p><h2 className="mt-1 text-3xl font-semibold">Release the right file to the right buyer.</h2><p className="mt-2 max-w-3xl text-slate-500">Every masked sample is attributed before it moves. No anonymous downloads.</p></header>
 <div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><Card className="p-6 md:p-8"><div className="flex items-start gap-4"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-50 text-blue-600"><FileSpreadsheet/></div><div><Pill tone="success">Active portfolio</Pill><h3 className="mt-2 text-xl font-semibold">{active.name}</h3><p className="mt-1 text-sm text-slate-500">{active.file?.name||'No approved masked file'}</p></div></div>
 {activeFileLocked&&<div className="mt-6 flex gap-3 rounded-2xl bg-amber-50 p-4 text-sm font-semibold text-amber-800"><LockKeyhole size={19}/>Distribution is locked while the portfolio is {active.status.replace('_',' ')}.</div>}
 {!prepared?<form onSubmit={submit} className="mt-8 space-y-5"><label><span className="mb-2 block text-sm font-semibold">Agency</span><select className={input} value={agencyId} onChange={e=>changeAgency(e.target.value)} required><option value="">Select an owned agency</option>{owned.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label><span className="mb-2 block text-sm font-semibold">Verified recipient</span><select className={input} value={contactId} onChange={e=>setContactId(e.target.value)} required><option value="">Select recipient</option>{agency?.contacts.map(c=><option key={c.id} value={c.id}>{c.firstName} {c.lastName} · {c.title}</option>)}</select></label>
 {prior.length>0&&<div className="flex gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4"><AlertTriangle className="shrink-0 text-amber-700"/><div><p className="font-semibold text-amber-900">Repeat distribution warning</p><p className="mt-1 text-sm text-amber-800">This recipient already received this portfolio {prior.length} time{prior.length===1?'':'s'}.</p></div></div>}
 <div><span className="mb-2 block text-sm font-semibold">Delivery method</span><div className="grid grid-cols-2 gap-3"><button type="button" onClick={()=>setMethod('email')} className={`rounded-2xl border p-4 text-left ${method==='email'?'border-blue-500 bg-blue-50':'border-slate-200'}`}><Mail size={19}/><p className="mt-3 font-semibold">Send by email</p><p className="mt-1 text-xs text-slate-500">Prepare an attributed outbound package.</p></button><button type="button" onClick={()=>setMethod('download')} className={`rounded-2xl border p-4 text-left ${method==='download'?'border-blue-500 bg-blue-50':'border-slate-200'}`}><Download size={19}/><p className="mt-3 font-semibold">Controlled download</p><p className="mt-1 text-xs text-slate-500">Download only after buyer selection.</p></button></div></div>
 <label><span className="mb-2 block text-sm font-semibold">Business reason</span><textarea className={`${input} min-h-24`} name="reason" required placeholder="Buyer requested masked sample after qualification call."/></label><label><span className="mb-2 block text-sm font-semibold">Required follow-up</span><input className={input} name="followUp" type="datetime-local" required min={new Date().toISOString().slice(0,16)}/></label><PrimaryButton className="w-full" disabled={!active.file||activeFileLocked||!owned.length}>Prepare distribution <ArrowRight className="ml-2" size={18}/></PrimaryButton>{!owned.length&&<p className="text-center text-sm text-amber-700">Add a decision-maker to one of your agencies first.</p>}</form>:<div className="mt-8"><div className="rounded-3xl bg-slate-950 p-6 text-white"><div className="flex items-center gap-3"><ShieldCheck className="text-blue-400"/><p className="font-semibold">Distribution attributed</p></div><div className="mt-6 space-y-4 text-sm"><Row label="Portfolio" value={prepared.portfolioName}/><Row label="Agency" value={prepared.agencyName}/><Row label="Recipient" value={`${prepared.contactName} · ${prepared.contactEmail}`}/><Row label="File" value={`${prepared.fileName} · version ${prepared.fileVersion}`}/><Row label="Method" value={prepared.method}/><Row label="Follow-up" value={new Date(prepared.followUpAt).toLocaleString()}/></div></div>{prepared.status==='prepared'?<PrimaryButton className="mt-5 w-full" onClick={deliver}>{prepared.method==='email'?<Mail className="mr-2" size={18}/>:<Download className="mr-2" size={18}/>} {prepared.method==='email'?'Confirm email sent':'Download attributed file'}</PrimaryButton>:<div className="mt-5 flex items-center justify-center gap-2 rounded-2xl bg-emerald-50 p-4 font-semibold text-emerald-700"><CheckCircle2/> Distribution recorded as {prepared.status}.</div>}<SecondaryButton className="mt-3 w-full" onClick={()=>{setPrepared(null);setNotice('')}}>Prepare another</SecondaryButton></div>}
 {notice&&<div className={`mt-5 rounded-2xl p-4 text-sm font-semibold ${notice.includes('Warning')?'bg-amber-50 text-amber-800':'bg-emerald-50 text-emerald-700'}`}>{notice}</div>}</Card>
 <div className="space-y-6"><Card className="p-6"><h3 className="font-semibold">Distribution controls</h3><div className="mt-5 space-y-4"><Rule text="A real agency and recipient are required."/><Rule text="The active approved file version is captured."/><Rule text="Repeat sends trigger a visible warning."/><Rule text="A follow-up is created with every distribution."/><Rule text="Reserved and sold portfolios automatically lock."/></div></Card><Link to="/employee/distributions"><Card className="flex items-center justify-between p-6 transition hover:-translate-y-0.5 hover:shadow-lg"><div><p className="font-semibold">Distribution history</p><p className="mt-1 text-sm text-slate-500">Review every sample you released.</p></div><ArrowRight className="text-blue-600"/></Card></Link></div></div></div>}
function Rule({text}:{text:string}){return <div className="flex gap-3 text-sm text-slate-600"><CheckCircle2 className="shrink-0 text-emerald-600" size={18}/>{text}</div>}
function Row({label,value}:{label:string;value:string}){return <div className="flex justify-between gap-6 border-b border-white/10 pb-3"><span className="text-slate-400">{label}</span><span className="text-right font-medium capitalize">{value}</span></div>}
function Empty({title,body}:{title:string;body:string}){return <div className="mx-auto max-w-3xl p-10"><Card className="p-10 text-center"><LockKeyhole className="mx-auto text-slate-300" size={40}/><h2 className="mt-5 text-2xl font-semibold">{title}</h2><p className="mt-2 text-slate-500">{body}</p></Card></div>}
