import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.45.4'
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'}
const respond=(status:number,payload:Record<string,unknown>)=>new Response(JSON.stringify(payload),{status,headers:{...cors,'content-type':'application/json'}})
async function gateway(url:string,key:string,params:Record<string,string>){const form=new URLSearchParams({security_key:key,...params});const response=await fetch(url,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:form});const text=await response.text();try{return JSON.parse(text)}catch{return Object.fromEntries(new URLSearchParams(text))}}
const last4=(value:unknown)=>{const digits=String(value||'').replace(/\D/g,'');return digits.length>=4?digits.slice(-4):null}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return respond(405,{error:'method'});try{
 const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,key=Deno.env.get('MAVERICK_PRIVATE_KEY')||Deno.env.get('NMI_SECURITY_KEY')||'';if(!key)return respond(500,{error:'processor key not configured'});const gatewayUrl=Deno.env.get('MAVERICK_NMI_ENDPOINT')||Deno.env.get('NMI_GATEWAY_URL')||'https://secure.nmi.com/api/transact.php';const auth=req.headers.get('Authorization')||'';const userDb=createClient(url,anon,{global:{headers:{Authorization:auth}}});const db=createClient(url,service);const {data:userResult,error:userError}=await userDb.auth.getUser();if(userError||!userResult.user)return respond(401,{error:'session required'});const {data:client}=await db.from('clients').select('id,user_id,maverick_customer_vault_id').eq('user_id',userResult.user.id).single();if(!client)return respond(403,{error:'client account required'});const body=await req.json();
 if(body.action==='delete'){const vault=String(client.maverick_customer_vault_id||'');if(vault){const result=await gateway(gatewayUrl,key,{customer_vault:'delete_customer',customer_vault_id:vault});if(String(result.response||result.response_code||'')!=='1')return respond(502,{deleted:false,message:String(result.responsetext||result.message||'Processor could not remove saved card.')})}await db.from('clients').update({maverick_customer_vault_id:null,maverick_payment_last4:null,maverick_payment_brand:null,maverick_payment_saved_at:null}).eq('id',client.id);return respond(200,{deleted:true})}
 const token=String(body.paymentToken||'');if(!token)return respond(400,{saved:false,message:'payment token required'});const oldVault=String(client.maverick_customer_vault_id||'');const result=await gateway(gatewayUrl,key,{customer_vault:'add_customer',payment_token:token});if(String(result.response||result.response_code||'')!=='1')return respond(402,{saved:false,message:String(result.responsetext||result.message||'Processor declined payment method.')});const newVault=String(result.customer_vault_id||result.customerVaultId||'');if(!newVault)return respond(502,{saved:false,message:'Processor did not return a vault id.'});const cardLast4=last4(result.cc_number||result.card_number||result.account_number),brand=String(result.card_type||result.card_brand||result.cc_type||'')||null;await db.from('clients').update({payment_processor:'maverick_easy_pay_direct',maverick_customer_vault_id:newVault,maverick_payment_last4:cardLast4,maverick_payment_brand:brand,maverick_payment_saved_at:new Date().toISOString()}).eq('id',client.id);if(oldVault&&oldVault!==newVault){await gateway(gatewayUrl,key,{customer_vault:'delete_customer',customer_vault_id:oldVault}).catch(()=>null)}return respond(200,{saved:true,last4:cardLast4,brand})
}catch(error){return respond(500,{error:error instanceof Error?error.message:'billing failed'})}})
