import { BarChart3, Bell, CalendarClock, ClipboardList, Crosshair, MessageSquare, Radio, Settings, Shield, Users } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useAuth } from '../modules/auth/AuthProvider'
import { acceptMarketplaceJob, getAgencyWorkspace, subscribeToMarketplace, type MarketplaceJobRow } from '../modules/marketplace/marketplaceRepository'
import { useAgencyGuardState } from '../modules/marketplace/useAgencyGuardState'
import { assignGuard, assignGuardSlot, getAgencyDispatchWorkspace, getJobStaffing, subscribeToDispatch, type AgencyDispatchWorkspace, type DispatchMission, type JobStaffing } from '../modules/dispatch/dispatchRepository'
import GuardsV4 from './GuardsV4'
import './design.css'

const items=[['marketplace','Marketplace',Crosshair],['operations','Operations',Radio],['scheduled','Scheduled',CalendarClock],['guards','Guards',Users],['assignments','Assignments',ClipboardList],['reports','Reports',Shield],['analytics','Analytics',BarChart3],['messages','Messages',MessageSquare],['settings','Settings',Settings]] as const
type Page=typeof items[number][0]
const copy:Record<Page,[string,string,string]>={marketplace:['Marketplace','Live coverage exchange','Claim verified work when your team has capacity.'],operations:['Operations','Dispatch command','Staff, launch and follow accepted missions.'],scheduled:['Scheduled','Upcoming coverage','See accepted work before it enters live operations.'],guards:['Guards','Your roster','Invite, verify and manage your field team.'],assignments:['Assignments','Won work','Every accepted marketplace mission in one place.'],reports:['Reports','Mission records','Review completed field work before publication.'],analytics:['Analytics','Agency performance','Capacity, utilization and marketplace performance.'],messages:['Messages','Guard communications','Direct, broadcast and mission-specific communication.'],settings:['Settings','Agency controls','Compliance, company profile and operational preferences.']}

function money(cents?:number|null){return cents?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(cents/100):'—'}
function activeCount(dispatch:AgencyDispatchWorkspace|null){return (dispatch?.missions??[]).filter(m=>!['open','completed','cancelled'].includes(m.status)).length}

export default function AgencyV4(){
  const auth=useAuth(); const [page,setPage]=useState<Page>('marketplace'); const [,title,desc]=copy[page]
  const live=auth.mode==='supabase'&&auth.role==='agency_admin'
  const guards=useAgencyGuardState(live)
  const [agencyName,setAgencyName]=useState('Agency')
  const [jobs,setJobs]=useState<MarketplaceJobRow[]>([])
  const [claimed,setClaimed]=useState<MarketplaceJobRow[]>([])
  const [dispatch,setDispatch]=useState<AgencyDispatchWorkspace|null>(null)
  const [loading,setLoading]=useState(live)
  const [claiming,setClaiming]=useState<string|null>(null)
  const [notice,setNotice]=useState('')
  const [operationBusy,setOperationBusy]=useState('')

  const refresh=async()=>{
    if(!live)return
    try{
      const [workspace,dispatchData]=await Promise.all([getAgencyWorkspace(),getAgencyDispatchWorkspace()])
      setAgencyName(workspace.name); setJobs(workspace.open); setClaimed(workspace.claimed); setDispatch(dispatchData); setNotice('')
    }catch(error){setNotice(error instanceof Error?error.message:'Unable to sync agency workspace.')}
    finally{setLoading(false)}
  }
  useEffect(()=>{void refresh()},[live])
  useEffect(()=>{if(!live)return;const timer=window.setInterval(()=>void refresh(),5000);const stopMarket=subscribeToMarketplace(()=>void refresh());const stopDispatch=subscribeToDispatch(()=>void refresh());return()=>{window.clearInterval(timer);stopMarket();stopDispatch()}},[live])
  const active=activeCount(dispatch)
  const sorted=useMemo(()=>[...jobs].sort((a,b)=>{const rank={emergency:0,priority:1,standard:2};return rank[a.priority]-rank[b.priority]}),[jobs])
  const claim=async(job:MarketplaceJobRow)=>{if(claiming)return;setClaiming(job.id);try{const result=await acceptMarketplaceJob(job.id);if(!result.accepted)throw new Error(result.reason||'This job is no longer available.');await refresh();setPage('operations')}catch(error){setNotice(error instanceof Error?error.message:'Unable to claim mission.')}finally{setClaiming(null)}}
  const assign=async(jobId:string,guardId:string,slotNumber?:number)=>{if(!guardId||operationBusy)return;const key=`${jobId}:${slotNumber??0}`;setOperationBusy(key);try{if(slotNumber)await assignGuardSlot(jobId,slotNumber,guardId);else await assignGuard(jobId,guardId);await refresh();setNotice('')}catch(error){setNotice(error instanceof Error?error.message:'Unable to assign guard.')}finally{setOperationBusy('')}}

  return <div className="v4-scope"><div className="v4-shell"><aside className="v4-rail"><div className="v4-brand"><div className="v4-brand-mark">CP</div><div>CO PILOT<small>SECURITY MARKETPLACE</small></div></div><nav className="v4-nav">{items.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><Icon/>{label}{id==='marketplace'&&jobs.length>0?<b className="v4-nav-count">{jobs.length}</b>:null}</button>)}</nav><div className="v4-rail-foot"><strong>{agencyName}</strong><span>{auth.user?.email??'Agency portal'}</span></div></aside><main className="v4-main"><header className="v4-topbar"><div><h1>{title}</h1><p>{agencyName} · {live?'Live':'Preview'}</p></div><div className="v4-actions"><button className="v4-button" aria-label="Notifications"><Bell size={16}/></button><button className="v4-button primary" onClick={()=>setPage('settings')}>Account</button></div></header><div className="v4-content">{notice&&<div className="v4-notice">{notice}</div>}<section className="v4-hero"><div><div className="v4-eyebrow">{copy[page][0]}</div><h2>{title}</h2><p>{desc}</p></div><span className="v4-system"><i/> {live?'LIVE SYSTEM':'PREVIEW'}</span></section>{page!=='operations'&&page!=='guards'?<section className="v4-grid"><div className="v4-card v4-metric"><span>Open jobs</span><strong>{jobs.length}</strong></div><div className="v4-card v4-metric"><span>Active missions</span><strong>{active}</strong></div><div className="v4-card v4-metric"><span>Online guards</span><strong>{guards.summary.online}</strong></div><div className="v4-card v4-metric"><span>Available</span><strong>{guards.summary.available}</strong></div></section>:null}{page==='marketplace'?<Marketplace jobs={sorted} loading={loading} claiming={claiming} onClaim={job=>void claim(job)} available={guards.summary.available}/>:page==='operations'?<Operations claimed={claimed} dispatch={dispatch} busy={operationBusy} onAssign={assign}/>:page==='guards'?<GuardsV4 live={live} onNotice={setNotice}/>:<MigrationPanel page={page}/>}</div></main></div><nav className="v4-mobile-nav">{items.slice(0,5).map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><Icon/>{label}</button>)}</nav></div>
}

function Marketplace({jobs,loading,claiming,onClaim,available}:{jobs:MarketplaceJobRow[];loading:boolean;claiming:string|null;onClaim:(job:MarketplaceJobRow)=>void;available:number}){return <section className="v4-stage"><div className="v4-panel"><div className="v4-panel-head"><h3>Open opportunities</h3><span><i className="v4-live-dot"/>Live</span></div><div className="v4-opportunities">{loading?<div className="v4-empty"><div><strong>Syncing marketplace</strong><span>Loading authorized opportunities.</span></div></div>:jobs.length===0?<div className="v4-empty"><div><strong>No open jobs right now</strong><span>New paid opportunities will appear here automatically.</span></div></div>:jobs.map(job=><article className="v4-job" key={job.id}><div className="v4-job-top"><span className={`v4-priority ${job.priority}`}>{job.priority==='emergency'?'Priority response':job.priority}</span><strong>{money(job.agency_payout_cents??job.payout_cents)}</strong></div><h3>{job.title}</h3><p>{job.property?.name||'Verified property'} · {job.property?.address||'Address available after claim'}</p><div className="v4-job-meta"><span>{Math.max(1,job.required_guards||1)} guard{Math.max(1,job.required_guards||1)===1?'':'s'}</span><span>{job.duration_minutes} min</span><span>{job.client?.display_name||'Marketplace client'}</span></div><button className="v4-button primary v4-claim" disabled={claiming===job.id} onClick={()=>onClaim(job)}>{claiming===job.id?'Claiming…':'Claim mission'}</button></article>)}</div></div><div className="v4-panel"><div className="v4-panel-head"><h3>Team readiness</h3><span>Live</span></div><div className="v4-list" style={{padding:14}}><div className="v4-row"><div><strong>Available guards</strong><small>Online and not assigned</small></div><span className="v4-badge">{available}</span></div><div className="v4-row"><div><strong>Marketplace access</strong><small>{available?'Capacity ready for work':'Bring a guard online to build capacity'}</small></div><span className="v4-badge">{available?'Open':'Standby'}</span></div></div></div></section>}
function Operations({claimed,dispatch,busy,onAssign}:{claimed:MarketplaceJobRow[];dispatch:AgencyDispatchWorkspace|null;busy:string;onAssign:(jobId:string,guardId:string,slotNumber?:number)=>Promise<void>}){
  const missions=dispatch?.missions??[]; const guards=(dispatch?.guards??[]).filter(g=>g.availability==='available'); const [staffing,setStaffing]=useState<Record<string,JobStaffing>>({})
  useEffect(()=>{let alive=true;const multi=missions.filter(m=>Math.max(1,m.required_guards??claimed.find(j=>j.id===m.job_id)?.required_guards??1)>1);if(!multi.length){setStaffing({});return()=>{alive=false}};void Promise.all(multi.map(async m=>[m.job_id,await getJobStaffing(m.job_id)] as const)).then(rows=>{if(alive)setStaffing(Object.fromEntries(rows))}).catch(()=>undefined);return()=>{alive=false}},[missions,claimed])
  const open=missions.filter(m=>!['completed','cancelled'].includes(m.status)); const needs=open.filter(m=>m.status==='awaiting_guard'||(!m.guard_id&&!m.multi_guard_slot)); const waiting=open.filter(m=>['offered','accepted'].includes(m.status)); const live=open.filter(m=>['en_route','arrived','active'].includes(m.status)); const buckets=[['Needs staffing',needs],['Guard response',waiting],['Live / on site',live]] as const
  const slotPanel=(m:DispatchMission)=>{const required=Math.max(1,m.required_guards??claimed.find(j=>j.id===m.job_id)?.required_guards??1);if(required<=1)return null;const state=staffing[m.job_id];const slots=state?.slots??Array.from({length:required},(_,i)=>({id:m.job_id+'-'+(i+1),slot_number:i+1,guard_id:null,status:'awaiting_guard' as const}));return <div className="v4-slots"><div className="v4-slot-summary"><strong>{state?.filled_slots??0}/{required} staffed</strong><span>{state?.accepted_slots??0} accepted</span></div>{slots.map(slot=>{const assigned=dispatch?.guards.find(g=>g.id===slot.guard_id);const key=m.job_id+':'+slot.slot_number;return <div className="v4-slot" key={slot.id}><div><strong>Guard {slot.slot_number} of {required}</strong><small>{assigned?assigned.name+' · '+slot.status.replaceAll('_',' '):'Open position'}</small></div>{slot.guard_id?<span className="v4-badge">{slot.status.replaceAll('_',' ')}</span>:<select disabled={!guards.length||busy===key} defaultValue="" onChange={e=>void onAssign(m.job_id,e.target.value,slot.slot_number)}><option value="" disabled>{guards.length?'Assign guard':'No guards available'}</option>{guards.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select>}</div>})}</div>}
  const card=(m:DispatchMission)=>{const required=Math.max(1,m.required_guards??claimed.find(j=>j.id===m.job_id)?.required_guards??1);const key=m.job_id+':0';return <article className="v4-operation" key={m.job_id+'-'+(m.slot_number??0)}><div className="v4-operation-top"><span className="v4-priority">{m.status.replaceAll('_',' ')}</span><small>{m.job_id.slice(0,8)}</small></div><h3>{m.title}</h3><p>{m.property.name} · {m.property.address}</p><div className="v4-job-meta"><span>{required} guard{required===1?'':'s'}</span><span>{m.duration_minutes} min</span><span>{m.priority}</span></div>{slotPanel(m)}{required===1&&(m.status==='awaiting_guard'||!m.guard_id)?<select className="v4-assign" disabled={!guards.length||busy===key} defaultValue="" onChange={e=>void onAssign(m.job_id,e.target.value)}><option value="" disabled>{guards.length?'Assign available guard':'No guards available'}</option>{guards.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select>:required===1?<div className="v4-assigned"><strong>{m.guard?.name||'Guard assigned'}</strong><span>{m.status.replaceAll('_',' ')}</span></div>:null}</article>}
  return <section className="v4-operations"><div className="v4-ops-summary"><div><span>Needs staffing</span><strong>{needs.length}</strong></div><div><span>Waiting</span><strong>{waiting.length}</strong></div><div><span>Live</span><strong>{live.length}</strong></div><div><span>Available guards</span><strong>{guards.length}</strong></div></div>{open.length===0?<section className="v4-panel"><div className="v4-empty"><div><strong>No active missions</strong><span>Claimed work moves here for staffing and execution.</span></div></div></section>:buckets.map(([label,list])=>list.length?<section className="v4-panel" key={label}><div className="v4-panel-head"><h3>{label}</h3><span>{list.length} mission{list.length===1?'':'s'}</span></div><div className="v4-operation-grid">{list.map(card)}</div></section>:null)}</section>
}
function MigrationPanel({page}:{page:Page}){return <section className="v4-panel"><div className="v4-panel-head"><h3>{copy[page][1]}</h3><span>V4</span></div><div className="v4-empty"><div><strong>{copy[page][0]} redesign queued</strong><span>The existing production engine remains intact while this workspace is migrated into the new shell.</span></div></div></section>}
