import { BarChart3, Bell, CalendarClock, ClipboardList, Crosshair, MessageSquare, Radio, Settings, Shield, Users } from 'lucide-react'
import { useState } from 'react'
import { useAuth } from '../modules/auth/AuthProvider'
import './design.css'

const items=[['marketplace','Marketplace',Crosshair],['operations','Operations',Radio],['scheduled','Scheduled',CalendarClock],['guards','Guards',Users],['assignments','Assignments',ClipboardList],['reports','Reports',Shield],['analytics','Analytics',BarChart3],['messages','Messages',MessageSquare],['settings','Settings',Settings]] as const
type Page=typeof items[number][0]
const copy:Record<Page,[string,string,string]>={marketplace:['Marketplace','Live coverage exchange','Claim verified work when your team has capacity.'],operations:['Operations','Dispatch command','Staff, launch and follow accepted missions.'],scheduled:['Scheduled','Upcoming coverage','See accepted work before it enters live operations.'],guards:['Guards','Your roster','Invite, verify and manage your field team.'],assignments:['Assignments','Won work','Every accepted marketplace mission in one place.'],reports:['Reports','Mission records','Review completed field work before publication.'],analytics:['Analytics','Agency performance','Capacity, utilization and marketplace performance.'],messages:['Messages','Guard communications','Direct, broadcast and mission-specific communication.'],settings:['Settings','Agency controls','Compliance, company profile and operational preferences.']}
export default function AgencyV4(){const auth=useAuth();const [page,setPage]=useState<Page>('marketplace');const [,title,desc]=copy[page];return <div className="v4-scope"><div className="v4-shell"><aside className="v4-rail"><div className="v4-brand"><div className="v4-brand-mark">CP</div><div>CO PILOT<small>SECURITY MARKETPLACE</small></div></div><nav className="v4-nav">{items.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><Icon/>{label}</button>)}</nav><div className="v4-rail-foot"><strong>Agency portal</strong><span>{auth.user?.email??'Connected'}</span></div></aside><main className="v4-main"><header className="v4-topbar"><div><h1>{title}</h1><p>Agency command center</p></div><div className="v4-actions"><button className="v4-button" aria-label="Notifications"><Bell size={16}/></button><button className="v4-button primary">Account</button></div></header><div className="v4-content"><section className="v4-hero"><div><div className="v4-eyebrow">{copy[page][0]}</div><h2>{title}</h2><p>{desc}</p></div><button className="v4-button">Live system</button></section><section className="v4-grid"><div className="v4-card v4-metric"><span>Open jobs</span><strong>0</strong></div><div className="v4-card v4-metric"><span>Active missions</span><strong>0</strong></div><div className="v4-card v4-metric"><span>Online guards</span><strong>1</strong></div><div className="v4-card v4-metric"><span>Reports</span><strong>0</strong></div></section><section className="v4-stage"><div className="v4-panel"><div className="v4-panel-head"><h3>{page==='marketplace'?'Open opportunities':title}</h3><span><i className="v4-live-dot"/>Live</span></div><div className="v4-empty"><div><strong>V4 presentation layer</strong><span>The existing Supabase engines will feed this workspace as each screen is migrated.</span></div></div></div><div className="v4-panel"><div className="v4-panel-head"><h3>Team readiness</h3><span>Live</span></div><div className="v4-list" style={{padding:14}}><div className="v4-row"><div><strong>Security Guard</strong><small>Online · available</small></div><span className="v4-badge">Ready</span></div><div className="v4-row"><div><strong>Marketplace</strong><small>Available when guard capacity is ready</small></div><span className="v4-badge">Open</span></div></div></div></section></div></main></div><nav className="v4-mobile-nav">{items.slice(0,5).map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><Icon/>{label}</button>)}</nav></div>}
