import { Activity, BadgeCheck, Bell, Building2, CreditCard, FileText, Gavel, Layers3, LogOut, MapPin, Radio, Settings, ShieldCheck, Users } from 'lucide-react'
import { useState } from 'react'
import { useAuth } from '../modules/auth/AuthProvider'
import './design.css'

type Page='overview'|'map'|'approvals'|'agencies'|'clients'|'documents'|'compliance'|'marketplace'|'live'|'payments'|'trust'|'settings'
const items:[Page,string,any][]=[['overview','Overview',Activity],['map','Global Map',MapPin],['approvals','Approvals',BadgeCheck],['agencies','Agencies',Building2],['clients','Clients',Users],['documents','Documents',FileText],['compliance','Compliance',ShieldCheck],['marketplace','Marketplace',Layers3],['live','Live Ops',Radio],['payments','Payments',CreditCard],['trust','Trust & Safety',Gavel],['settings','Settings',Settings]]
const copy:Record<Page,[string,string]>={overview:['Platform overview','See the health of the entire security marketplace at a glance.'],map:['Global command map','Monitor live platform coverage from one command view.'],approvals:['Approval center','Review agencies, clients, credentials and submitted documents.'],agencies:['Agency governance','Manage security companies operating on the marketplace.'],clients:['Client governance','Manage client access, risk and marketplace standing.'],documents:['Document review','Review licensing, insurance and compliance files.'],compliance:['Compliance','Control marketplace eligibility and operating requirements.'],marketplace:['Marketplace','See marketplace supply, demand and exceptions.'],live:['Live operations','Monitor missions, guards and critical platform events.'],payments:['Payments & payouts','Control marketplace money movement and reconciliation.'],trust:['Trust & safety','Handle disputes, complaints, suspensions and escalations.'],settings:['Platform settings','Manage owner-level platform controls.']}
export default function OwnerV4({preview=false}:{preview?:boolean}){const auth=useAuth();const live=auth.mode==='supabase'&&auth.role==='platform_admin'&&!preview;const[page,setPage]=useState<Page>('overview');const[title,desc]=copy[page];return <div className="v4-scope"><div className="v4-shell"><aside className="v4-rail"><div className="v4-brand"><div className="v4-brand-mark">CP</div><div>CO PILOT<small>OWNER COMMAND</small></div></div><nav className="v4-nav">{items.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><Icon/>{label}</button>)}</nav><div className="v4-rail-foot"><strong>{auth.profile?.full_name||'Platform Owner'}</strong><span>{auth.user?.email??'Owner portal'}</span><button className="v4-logout" type="button" onClick={()=>void auth.signOut()}><LogOut size={15}/><span>Log out</span></button></div></aside><main className="v4-main"><header className="v4-topbar"><div><h1>{title}</h1><p>Owner console · {live?'Live':'Preview'}</p></div><div className="v4-actions"><button className="v4-button" aria-label="Notifications"><Bell size={16}/></button><button className="v4-button primary" onClick={()=>setPage('settings')}>Account</button></div></header><div className="v4-content"><section className="v4-hero"><div><div className="v4-eyebrow">OWNER CONSOLE</div><h2>{title}</h2><p>{desc}</p></div><span className="v4-system"><i/> {live?'LIVE SYSTEM':'PREVIEW'}</span></section><section className="v4-grid v4-summary-grid"><div className="v4-card v4-metric"><span>Agencies</span><strong>—</strong></div><div className="v4-card v4-metric"><span>Live missions</span><strong>—</strong></div><div className="v4-card v4-metric"><span>Online guards</span><strong>—</strong></div><div className="v4-card v4-metric"><span>Needs attention</span><strong>—</strong></div></section><section className="v4-panel"><div className="v4-panel-head"><h3>{title}</h3><span>V4</span></div><div className="v4-empty"><div><strong>New owner workspace</strong><span>This is a clean V4 slate. Proven production engines will be connected screen by screen after each new interface is designed and approved.</span></div></div></section></div></main></div><nav className="v4-mobile-nav">{items.slice(0,5).map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><Icon/>{label}</button>)}</nav></div>}
