import { useEffect,useMemo,useState } from 'react'
import { AlertTriangle,CheckCircle2,Clock3,FileText,Image,MapPin,Printer,Send,ShieldCheck,X } from 'lucide-react'
import { getAgencyReports,reviewMissionReport,subscribeToReports,type MissionReportRecord } from '../modules/reporting/reportingRepository'

export default function ReportsV4({live,onNotice}:{live:boolean;onNotice:(message:string)=>void}){
 const[reports,setReports]=useState<MissionReportRecord[]>([]),[selected,setSelected]=useState<MissionReportRecord|null>(null),[loading,setLoading]=useState(live),[note,setNote]=useState(''),[busy,setBusy]=useState(false)
 const load=async()=>{if(!live){setLoading(false);return}try{const rows=await getAgencyReports();setReports(rows);setSelected(current=>current?rows.find(r=>r.id===current.id)??null:null);onNotice('')}catch(e){onNotice(e instanceof Error?e.message:'Reports unavailable')}finally{setLoading(false)}}
 useEffect(()=>{void load();if(!live)return;return subscribeToReports(()=>void load())},[live])
 const counts=useMemo(()=>({pending:reports.filter(r=>r.status==='pending_review').length,clarify:reports.filter(r=>r.status==='clarification_requested').length,published:reports.filter(r=>r.status==='published').length,total:reports.length}),[reports])
 const act=async(action:'publish'|'clarification')=>{if(!selected)return;setBusy(true);try{await reviewMissionReport(selected.id,action,note);setNote('');await load();onNotice(action==='publish'?'Report published to client.':'Clarification requested.')}catch(e){onNotice(e instanceof Error?e.message:'Report action failed')}finally{setBusy(false)}}
 return <section className="v4-reports"><div className="v4-report-summary"><div><span>Pending review</span><strong>{counts.pending}</strong></div><div><span>Clarification</span><strong>{counts.clarify}</strong></div><div><span>Published</span><strong>{counts.published}</strong></div><div><span>Total reports</span><strong>{counts.total}</strong></div></div><section className="v4-panel"><div className="v4-panel-head"><h3>Mission reports</h3><span>{loading?'Syncing…':'Immutable mission records'}</span></div><div className="v4-report-list">{!loading&&reports.length===0?<div className="v4-empty"><div><FileText/><strong>No completed mission reports</strong><span>Reports are created by the existing Mission Engine after completed work.</span></div></div>:reports.map(r=>{const s=r.snapshot;const guards=Array.isArray(s?.guards)?s.guards:[];const required=s?.staffing?.required_guards??(guards.length||1);const completed=s?.staffing?.completed_guards??(guards.length||1);return <button type="button" className="v4-report-row" key={r.id} onClick={()=>{setSelected(r);setNote(r.agency_review_note??'')}}><div><span className="v4-badge">{r.status.replaceAll('_',' ')}</span><h3>{s?.job?.title??'Completed mission'}</h3><p><MapPin/> {s?.property?.name??'Property'} · {s?.property?.address??''}</p></div><div className="v4-report-meta"><strong>{completed}/{required} guards</strong><span>{new Date(r.created_at).toLocaleString()}</span></div></button>})}</div></section>{selected?<ReportDetail report={selected} note={note} setNote={setNote} busy={busy} publish={()=>void act('publish')} clarify={()=>void act('clarification')} close={()=>setSelected(null)}/>:null}</section>
}
function ReportDetail({report,note,setNote,busy,publish,clarify,close}:{report:MissionReportRecord;note:string;setNote:(v:string)=>void;busy:boolean;publish:()=>void;clarify:()=>void;close:()=>void}){
 const s=report.snapshot,guards=Array.isArray(s?.guards)?s.guards:[],multi=guards.length>0,m=multi?{}:(s?.mission??{}),e=multi?guards.flatMap((x:any)=>Array.isArray(x?.mission?.evidence)?x.mission.evidence:[]):(Array.isArray(m.evidence)?m.evidence:[]),timeline=Array.isArray(s?.timeline)?s.timeline:[],required=multi?(s?.staffing?.required_guards??guards.length):1,completed=multi?(s?.staffing?.completed_guards??guards.length):1,complete=completed>=required,completedAt=multi?s?.job?.completed_at:m.completed_at,guardLabel=multi?`${completed}/${required} guards`:(s?.guard?.name??'Guard')
 return <article className="v4-report-detail v4-panel"><header><div><small>REPORT v{report.version}.0</small><h2>{s?.job?.title??'Mission report'}</h2><p>{s?.property?.name} · {s?.property?.address}</p></div><button className="v4-button" type="button" onClick={close}><X/></button></header><div className="v4-report-metrics"><span><Clock3/><b>{completedAt?new Date(completedAt).toLocaleString():'Completed'}</b><small>Completion</small></span><span><ShieldCheck/><b>{guardLabel}</b><small>{multi?'Staffing':'Guard'}</small></span><span><CheckCircle2/><b>{complete?'Complete':'Incomplete'}</b><small>Mission state</small></span><span><Image/><b>{e.reduce((n:number,x:any)=>n+(x.photos||0)+(x.videos||0)+(x.note?1:0),0)}</b><small>Evidence</small></span></div>{multi?<section><h3>Guard coverage</h3><div className="v4-report-checks">{guards.map((x:any)=><div key={x.slot_number}><ShieldCheck/><span><b>Guard {x.slot_number} of {required}</b><small>{x?.guard?.name??'Guard'} · {x?.mission?.state??'unknown'} · {x?.mission?.checkpoint_index??0}/6 checkpoints</small></span></div>)}</div></section>:null}<section><h3>Mission timeline</h3><div className="v4-report-timeline">{timeline.length?timeline.map((x:any)=><div key={x.id}><i/><span><b>{String(x.event_type).replaceAll('_',' ')}</b><small>{new Date(x.created_at).toLocaleString()} · {x.actor_name??'System'}</small></span></div>):<p>No timeline events in this snapshot.</p>}</div></section><section><h3>Agency review</h3>{!complete?<div className="v4-report-warning"><AlertTriangle/>Final publication is locked until all {required} required guards complete the mission.</div>:null}<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Optional client-facing review note" disabled={report.status==='published'}/>{report.status!=='published'?<div className="v4-report-actions"><button className="v4-button" type="button" onClick={clarify} disabled={busy||!note.trim()}><AlertTriangle/>Return for clarification</button><button className="v4-button primary" type="button" onClick={publish} disabled={busy||!complete}><Send/>Publish to client</button></div>:<div className="v4-report-published"><CheckCircle2/>Published to client {report.published_at&&new Date(report.published_at).toLocaleString()}<button className="v4-button" type="button" onClick={()=>window.print()}><Printer/>Print / Save PDF</button></div>}</section></article>
}
