import { useEffect, useMemo, useRef, useState } from 'react'
import { Building2, LocateFixed, MapPin, Navigation } from 'lucide-react'
import { loadGoogleMaps } from './googleMapsLoader'

export type MarketplaceMapJob={id:string;title:string;kind:'standard'|'priority'|'emergency';latitude:number|null;longitude:number|null}
export type MarketplaceMapGuard={id:string;name:string;status:string;latitude:number|null;longitude:number|null;freshness?:string|null}

type Props={
 jobs:MarketplaceMapJob[]; guards:MarketplaceMapGuard[]; selectedJobId:string|null; selectedGuardId?:string|null;
 rangeMiles:number; showJobs:boolean; showGuards:boolean; onSelectJob:(id:string)=>void
}
const DARK=[{elementType:'geometry',stylers:[{color:'#091722'}]},{elementType:'labels.text.stroke',stylers:[{color:'#091722'}]},{elementType:'labels.text.fill',stylers:[{color:'#8297aa'}]},{featureType:'poi',stylers:[{visibility:'off'}]},{featureType:'road',elementType:'geometry',stylers:[{color:'#183043'}]},{featureType:'road',elementType:'geometry.stroke',stylers:[{color:'#0c1d2a'}]},{featureType:'road.highway',elementType:'geometry',stylers:[{color:'#21445e'}]},{featureType:'transit',stylers:[{visibility:'off'}]},{featureType:'water',elementType:'geometry',stylers:[{color:'#06101a'}]}]
const svg=(s:string)=>`data:image/svg+xml;charset=UTF-8,${encodeURIComponent(s)}`
const jobIcon=(kind:string,selected:boolean)=>svg(`<svg xmlns="http://www.w3.org/2000/svg" width="58" height="58"><circle cx="29" cy="29" r="${selected?27:23}" fill="${kind==='emergency'?'#ef445c':kind==='priority'?'#ff8b2c':'#ffc82f'}" fill-opacity=".24"/><circle cx="29" cy="29" r="16" fill="${kind==='emergency'?'#ef445c':kind==='priority'?'#ff8b2c':'#ffc82f'}"/><path d="M21 28l8-6 8 6v10H21z" fill="none" stroke="#fff" stroke-width="2"/><path d="M26 38v-6h6v6" fill="none" stroke="#fff" stroke-width="2"/></svg>`)
const guardIcon=svg('<svg xmlns="http://www.w3.org/2000/svg" width="52" height="52"><circle cx="26" cy="26" r="24" fill="#1684ff" fill-opacity=".22"/><circle cx="26" cy="26" r="16" fill="#1684ff"/><path d="M26 17.5 33 20v5.5c0 4.6-2.8 8.2-7 10-4.2-1.8-7-5.4-7-10V20z" fill="none" stroke="white" stroke-width="2"/></svg>')
const valid=(lat:number|null,lng:number|null)=>typeof lat==='number'&&typeof lng==='number'&&Number.isFinite(lat)&&Number.isFinite(lng)?{lat,lng}:null
const miles=(a:{lat:number;lng:number},b:{lat:number;lng:number})=>{const r=3958.8,dLat=(b.lat-a.lat)*Math.PI/180,dLng=(b.lng-a.lng)*Math.PI/180,x=Math.sin(dLat/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(dLng/2)**2;return 2*r*Math.asin(Math.sqrt(x))}

export default function MarketplaceDynamicMap({jobs,guards,selectedJobId,selectedGuardId,rangeMiles,showJobs,showGuards,onSelectJob}:Props){
 const host=useRef<HTMLDivElement|null>(null),map=useRef<any>(null),jobMarkers=useRef<Map<string,any>>(new Map()),guardMarkers=useRef<Map<string,any>>(new Map()),route=useRef<any>(null),service=useRef<any>(null),circle=useRef<any>(null)
 const [ready,setReady]=useState(false),[routeState,setRouteState]=useState<'idle'|'live'|'unavailable'>('idle')
 const guardPoints=useMemo(()=>guards.map(g=>({g,p:valid(g.latitude,g.longitude)})).filter(v=>v.p&&v.g.status!=='offline'&&v.g.freshness!=='expired') as {g:MarketplaceMapGuard;p:{lat:number;lng:number}}[],[guards])
 const center=useMemo(()=>{if(guardPoints.length)return {lat:guardPoints.reduce((s,v)=>s+v.p.lat,0)/guardPoints.length,lng:guardPoints.reduce((s,v)=>s+v.p.lng,0)/guardPoints.length};const first=jobs.map(j=>valid(j.latitude,j.longitude)).find(Boolean);return first??null},[guardPoints,jobs])
 const visibleJobs=useMemo(()=>jobs.filter(j=>{const p=valid(j.latitude,j.longitude);return p&&(!center||miles(center,p)<=rangeMiles)}),[jobs,center?.lat,center?.lng,rangeMiles])
 const outside=Math.max(0,jobs.filter(j=>valid(j.latitude,j.longitude)).length-visibleJobs.length)
 useEffect(()=>{let dead=false;(async()=>{if(!host.current)return;try{const google=await loadGoogleMaps();if(dead||!host.current)return;map.current=new google.maps.Map(host.current,{center:center??{lat:27.95,lng:-82.45},zoom:11,disableDefaultUI:true,clickableIcons:false,gestureHandling:'cooperative',styles:DARK,backgroundColor:'#091722'});service.current=new google.maps.DirectionsService();route.current=new google.maps.DirectionsRenderer({map:map.current,suppressMarkers:true,preserveViewport:true,polylineOptions:{strokeColor:'#1684ff',strokeOpacity:.95,strokeWeight:6}});setReady(true)}catch{setReady(false)}})();return()=>{dead=true;jobMarkers.current.forEach(m=>m.setMap(null));guardMarkers.current.forEach(m=>m.setMap(null));route.current?.setMap(null);circle.current?.setMap(null)}},[])
 useEffect(()=>{if(!ready||!map.current||!window.google?.maps)return;const google=window.google;jobMarkers.current.forEach(m=>m.setMap(null));jobMarkers.current.clear();guardMarkers.current.forEach(m=>m.setMap(null));guardMarkers.current.clear();
  if(showJobs)visibleJobs.forEach(j=>{const p=valid(j.latitude,j.longitude);if(!p)return;const selected=j.id===selectedJobId;const marker=new google.maps.Marker({map:map.current,position:p,title:j.title,zIndex:selected?8:4,icon:{url:jobIcon(j.kind,selected),scaledSize:new google.maps.Size(58,58),anchor:new google.maps.Point(29,29)}});marker.addListener('click',()=>onSelectJob(j.id));jobMarkers.current.set(j.id,marker)})
  if(showGuards)guardPoints.forEach(({g,p})=>{const marker=new google.maps.Marker({map:map.current,position:p,title:g.name,zIndex:g.id===selectedGuardId?9:5,icon:{url:guardIcon,scaledSize:new google.maps.Size(52,52),anchor:new google.maps.Point(26,26)}});guardMarkers.current.set(g.id,marker)})
  if(center){circle.current?.setMap(null);circle.current=new google.maps.Circle({map:map.current,center,radius:rangeMiles*1609.344,strokeColor:'#1684ff',strokeOpacity:.42,strokeWeight:1,fillColor:'#1684ff',fillOpacity:.025,clickable:false})}
  const bounds=new google.maps.LatLngBounds();if(showJobs)visibleJobs.forEach(j=>{const p=valid(j.latitude,j.longitude);if(p)bounds.extend(p)});if(showGuards)guardPoints.forEach(v=>bounds.extend(v.p));if(!bounds.isEmpty())map.current.fitBounds(bounds,{top:64,right:64,bottom:86,left:64});else if(center){map.current.setCenter(center);map.current.setZoom(rangeMiles<=5?12:rangeMiles<=15?10:9)}
 },[ready,visibleJobs,guardPoints,showJobs,showGuards,selectedJobId,selectedGuardId,rangeMiles])
 useEffect(()=>{if(!ready||!service.current||!window.google?.maps)return;const job=visibleJobs.find(j=>j.id===selectedJobId),guard=guardPoints.find(v=>v.g.id===selectedGuardId);const jp=job&&valid(job.latitude,job.longitude);if(!jp||!guard){route.current?.setDirections({routes:[]});setRouteState('idle');return}service.current.route({origin:guard.p,destination:jp,travelMode:window.google.maps.TravelMode.DRIVING,provideRouteAlternatives:false},(result:any,status:string)=>{if(status==='OK'&&result){route.current?.setDirections(result);setRouteState('live')}else{route.current?.setDirections({routes:[]});setRouteState('unavailable')}})},[ready,selectedJobId,selectedGuardId,visibleJobs,guardPoints])
 return <div className="marketplace-dynamic-map"><div ref={host} className="marketplace-google-map"/>{outside>0&&<div className="map-outside-count">{outside} job{outside===1?'':'s'} outside {rangeMiles} mi range</div>}<div className={`dynamic-route-state ${routeState}`}>{routeState==='live'?<Navigation/>:<LocateFixed/>}{routeState==='live'?'FASTEST ROUTE LIVE':routeState==='unavailable'?'ROUTE UNAVAILABLE':'LIVE MARKET VIEW'}</div><div className="dynamic-map-summary"><MapPin/><span><small>MARKETPLACE COVERAGE</small><strong>{visibleJobs.length} open job{visibleJobs.length===1?'':'s'} · {rangeMiles} mi</strong></span></div>{!ready&&<div className="dynamic-map-empty"><Building2/><strong>Loading live marketplace map</strong></div>}</div>
}
