import { useEffect, useState, type FormEvent } from 'react'
import { FileCheck2, RefreshCw, Send, UploadCloud } from 'lucide-react'
import { getMyAgencyDocuments, subscribeToDocuments, submitAgencyApplication, uploadAgencyDocument, type AgencyDocumentCenter as Center } from './documentRepository'

const docTypes=[['agency_license','Agency license'],['general_liability','General liability / COI'],['w9','W-9'],['armed_endorsement','Armed endorsement'],['guard_license','Guard license'],['business_license','Business license']]
const services=['unarmed','armed','mobile_patrol','event_security','alarm_response','construction_site']
export default function AgencyDocumentCenter(){
  const[center,setCenter]=useState<Center|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[appBusy,setAppBusy]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('')
  const[owner,setOwner]=useState('');const[states,setStates]=useState('FL');const[appServices,setAppServices]=useState<string[]>(['unarmed']);const[license,setLicense]=useState('');const[appNote,setAppNote]=useState('')
  const[documentType,setDocumentType]=useState('agency_license');const[state,setState]=useState('FL');const[service,setService]=useState('unarmed');const[expires,setExpires]=useState('');const[note,setNote]=useState('');const[file,setFile]=useState<File|null>(null)
  const load=async()=>{try{setCenter(await getMyAgencyDocuments());setError('')}catch(e){setError(e instanceof Error?e.message:'Documents unavailable')}finally{setLoading(false)}}
  useEffect(()=>{void load();return subscribeToDocuments(()=>void load())},[])
  const submitApplication=async(e:FormEvent)=>{e.preventDefault();setAppBusy(true);try{await submitAgencyApplication({ownerContactName:owner,operatingStates:states.split(',').map(s=>s.trim().toUpperCase()).filter(Boolean),serviceCategories:appServices,licenseNumber:license,note:appNote});setNotice('Agency application submitted for owner/admin review.');await load()}catch(err){setError(err instanceof Error?err.message:'Application failed')}finally{setAppBusy(false)}}
  const submit=async(e:FormEvent)=>{e.preventDefault();if(!file){setError('Choose a PDF or image first.');return}setBusy(true);try{await uploadAgencyDocument({file,documentType,operatingState:state,serviceCategory:service,expiresOn:expires,note});setFile(null);setExpires('');setNote('');setNotice('Document submitted for owner review.');await load()}catch(err){setError(err instanceof Error?err.message:'Upload failed')}finally{setBusy(false)}}
  return <section className="agency-document-center"><div className="operations-heading compact"><div><span className="eyebrow">COMPLIANCE + APPLICATION</span><h1>Agency approval center</h1><p>Submit your company profile, service states, licenses, insurance, W-9, and state-specific files for owner/admin approval.</p></div><button type="button" onClick={()=>void load()}><RefreshCw/>Refresh</button></div>{error&&<p className="agency-doc-alert">{error}</p>}{notice&&<p className="agency-doc-success">{notice}</p>}
    <div className="agency-doc-grid"><form className="operation-card agency-doc-form" onSubmit={submitApplication}><div className="operation-status"><span>APPLICATION</span><small>{center?.agency.status ?? 'pending'}</small></div><h3>Company onboarding</h3><label>Owner/contact name<input value={owner} onChange={e=>setOwner(e.target.value)} placeholder="Owner or compliance contact" required/></label><label>Operating states<input value={states} onChange={e=>setStates(e.target.value)} placeholder="FL, GA, TX"/></label><label>Agency license number<input value={license} onChange={e=>setLicense(e.target.value)} placeholder="State license number"/></label><div className="agency-service-checks">{services.map(v=><button type="button" key={v} className={appServices.includes(v)?'active':''} onClick={()=>setAppServices(s=>s.includes(v)?s.filter(x=>x!==v):[...s,v])}>{v.replaceAll('_',' ')}</button>)}</div><label>Application note<textarea value={appNote} onChange={e=>setAppNote(e.target.value)} placeholder="Services, armed/unarmed scope, states, special compliance info"/></label><button className="primary" disabled={appBusy} type="submit"><Send/>{appBusy?'Submitting…':'Submit application'}</button></form>
    <form className="operation-card agency-doc-form" onSubmit={submit}><div className="operation-status"><span>DOCUMENTS</span><small>{center?.compliance.status ?? 'checking'}</small></div><h3>Upload required file</h3><label>Document type<select value={documentType} onChange={e=>setDocumentType(e.target.value)}>{docTypes.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>State<input value={state} onChange={e=>setState(e.target.value.toUpperCase())} maxLength={2}/></label><label>Service category<select value={service} onChange={e=>setService(e.target.value)}>{services.map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>)}</select></label><label>Expiration date<input type="date" value={expires} onChange={e=>setExpires(e.target.value)}/></label><label>File<input type="file" accept="application/pdf,image/*" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><label>Note<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Anything owner/admin should know"/></label><button className="primary" disabled={busy} type="submit"><UploadCloud/>{busy?'Uploading…':'Upload for review'}</button></form></div>
    <div className="operation-card agency-doc-list"><div className="operation-status"><span>{loading?'LOADING':'REVIEW STATUS'}</span><small>{center?.documents.length ?? 0} files</small></div><h3>Compliance checklist</h3>{center?.compliance.missing?.length?<p className="agency-doc-alert">Missing: {center.compliance.missing.join(', ').replaceAll('_',' ')}</p>:<p className="agency-doc-success">Required baseline documents are approved.</p>}{center?.documents.length?center.documents.map(d=><article key={d.id}><FileCheck2/><div><strong>{docTypes.find(([v])=>v===d.document_type)?.[1]??d.document_type}</strong><small>{d.status.replace('_',' ')} · {d.operating_state} · expires {d.expires_on ?? 'N/A'}</small>{d.review_note&&<em>{d.review_note}</em>}</div></article>):<p>No documents submitted yet.</p>}</div>
  </section>
}
