import { useEffect, useState, type FormEvent } from 'react'
import { FileCheck2, RefreshCw, UploadCloud } from 'lucide-react'
import { getMyAgencyDocuments, subscribeToDocuments, uploadAgencyDocument, type AgencyDocumentCenter as Center } from './documentRepository'

const docTypes=[['agency_license','Agency license'],['general_liability','General liability / COI'],['w9','W-9'],['armed_endorsement','Armed endorsement'],['guard_license','Guard license'],['business_license','Business license'],['property_authorization','Property authorization']]
export default function AgencyDocumentCenter(){
  const[center,setCenter]=useState<Center|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('')
  const[documentType,setDocumentType]=useState('agency_license');const[state,setState]=useState('FL');const[service,setService]=useState('unarmed');const[expires,setExpires]=useState('');const[note,setNote]=useState('');const[file,setFile]=useState<File|null>(null)
  const load=async()=>{try{setCenter(await getMyAgencyDocuments());setError('')}catch(e){setError(e instanceof Error?e.message:'Documents unavailable')}finally{setLoading(false)}}
  useEffect(()=>{void load();return subscribeToDocuments(()=>void load())},[])
  const submit=async(e:FormEvent)=>{e.preventDefault();if(!file){setError('Choose a PDF or image first.');return}setBusy(true);try{await uploadAgencyDocument({file,documentType,operatingState:state,serviceCategory:service,expiresOn:expires,note});setFile(null);setExpires('');setNote('');setNotice('Document submitted for owner review.');await load()}catch(err){setError(err instanceof Error?err.message:'Upload failed')}finally{setBusy(false)}}
  return <section className="agency-document-center"><div className="operations-heading compact"><div><span className="eyebrow">COMPLIANCE DOCUMENTS</span><h1>Agency document center</h1><p>Upload licenses, insurance, W-9, and state-specific files for owner/admin approval.</p></div><button type="button" onClick={()=>void load()}><RefreshCw/>Refresh</button></div>{error&&<p className="agency-doc-alert">{error}</p>}{notice&&<p className="agency-doc-success">{notice}</p>}<div className="agency-doc-grid"><form className="operation-card agency-doc-form" onSubmit={submit}><div className="operation-status"><span>PENDING REVIEW</span><small>{center?.compliance.status ?? 'checking'}</small></div><h3>Submit document</h3><label>Document type<select value={documentType} onChange={e=>setDocumentType(e.target.value)}>{docTypes.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>State<input value={state} onChange={e=>setState(e.target.value.toUpperCase())} maxLength={2}/></label><label>Service category<select value={service} onChange={e=>setService(e.target.value)}><option value="unarmed">Unarmed</option><option value="armed">Armed</option><option value="patrol">Patrol</option><option value="event">Event</option><option value="alarm_response">Alarm response</option></select></label><label>Expiration date<input type="date" value={expires} onChange={e=>setExpires(e.target.value)}/></label><label>File<input type="file" accept="application/pdf,image/*" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><label>Note<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Anything owner/admin should know"/></label><button className="primary" disabled={busy} type="submit"><UploadCloud/>{busy?'Uploading…':'Upload for review'}</button></form><div className="operation-card agency-doc-list"><div className="operation-status"><span>{loading?'LOADING':'DOCUMENTS'}</span><small>{center?.documents.length ?? 0} files</small></div><h3>Review status</h3>{center?.documents.length?center.documents.map(d=><article key={d.id}><FileCheck2/><div><strong>{docTypes.find(([v])=>v===d.document_type)?.[1]??d.document_type}</strong><small>{d.status.replace('_',' ')} · {d.operating_state} · expires {d.expires_on ?? 'N/A'}</small>{d.review_note&&<em>{d.review_note}</em>}</div></article>):<p>No documents submitted yet.</p>}</div></div></section>
}
