import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export type AgencyStatus='new'|'researching'|'contacting'|'follow_up_due'|'decision_maker_reached'|'interested'|'sample_requested'|'offer_expected'|'not_interested'|'do_not_contact'|'dormant';
export type ActivityType='call'|'email'|'note'|'follow_up';
export type ActivityDisposition='No answer'|'Left voicemail'|'Gatekeeper'|'Wrong number'|'Email sent'|'Email bounced'|'Spoke with decision-maker'|'Requested portfolio'|'Interested'|'Not interested'|'Do not contact'|'Follow-up completed';
export interface AgencyContact{ id:string; firstName:string; lastName:string; title:string; email:string; phone:string; decisionMaker:boolean; }
export interface AgencyActivity{ id:string; type:ActivityType; disposition:ActivityDisposition|string; notes:string; occurredAt:string; contactId?:string; followUpAt?:string; completedAt?:string; }
export interface Agency{ id:string; name:string; website:string; phone:string; generalEmail:string; city:string; state:string; sourceUrl:string; ownerEmployeeId:string; ownerEmployeeName:string; ownershipStartedAt:string; ownershipExpiresAt:string; status:AgencyStatus; contacts:AgencyContact[]; activities:AgencyActivity[]; createdAt:string; }

type DuplicateMatch={agency:Agency;score:number;reasons:string[]};
type Store={agencies:Agency[];currentEmployee:{id:string;name:string};duplicateCheck:(input:{name:string;website:string;phone:string;generalEmail:string})=>DuplicateMatch[];createAgency:(input:Omit<Agency,'id'|'createdAt'|'contacts'|'activities'|'ownerEmployeeId'|'ownerEmployeeName'|'ownershipStartedAt'|'ownershipExpiresAt'|'status'>)=>Agency;addContact:(agencyId:string,input:Omit<AgencyContact,'id'>)=>void;addActivity:(agencyId:string,input:Omit<AgencyActivity,'id'|'occurredAt'>)=>void;completeFollowUp:(agencyId:string,activityId:string)=>void;snoozeFollowUp:(agencyId:string,activityId:string,nextDate:string)=>void;reassign:(agencyId:string,name:string)=>void;release:(agencyId:string)=>void;get:(id:string)=>Agency|undefined;};
const KEY='dmh-sales-os-agencies-v040';
const now=Date.now();
const seed:Agency[]=[{id:'agency-demo',name:'Atlas Recovery Partners',website:'https://atlasrecovery.example',phone:'813-555-0168',generalEmail:'buyers@atlasrecovery.example',city:'Tampa',state:'FL',sourceUrl:'https://maps.google.com',ownerEmployeeId:'employee-demo',ownerEmployeeName:'Sarah Johnson',ownershipStartedAt:new Date(now-86400000*8).toISOString(),ownershipExpiresAt:new Date(now+86400000*22).toISOString(),status:'follow_up_due',createdAt:new Date(now-86400000*8).toISOString(),contacts:[{id:'contact-demo',firstName:'Michael',lastName:'Reed',title:'Portfolio Acquisition Manager',email:'mreed@atlasrecovery.example',phone:'813-555-0191',decisionMaker:true}],activities:[{id:'activity-demo',type:'call',disposition:'Spoke with decision-maker',notes:'Interested in lease-to-own paper. Requested masked sample after internal review.',occurredAt:new Date(now-86400000).toISOString(),followUpAt:new Date(now-3600000).toISOString()}]}];
const Context=createContext<Store|null>(null);
const normalize=(v:string)=>v.toLowerCase().replace(/^https?:\/\/(www\.)?/,'').replace(/\/$/,'').replace(/[^a-z0-9]/g,'');
function statusFromDisposition(disposition:string,hasFollowUp:boolean):AgencyStatus{if(disposition==='Do not contact')return'do_not_contact';if(disposition==='Not interested')return'not_interested';if(disposition==='Requested portfolio')return'sample_requested';if(disposition==='Interested')return'interested';if(disposition==='Spoke with decision-maker')return'decision_maker_reached';if(hasFollowUp)return'follow_up_due';if(['No answer','Left voicemail','Gatekeeper','Email sent'].includes(disposition))return'contacting';return'researching'}
export function AgencyProvider({children}:{children:ReactNode}){const [agencies,setAgencies]=useState<Agency[]>(()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')||seed}catch{return seed}});useEffect(()=>localStorage.setItem(KEY,JSON.stringify(agencies)),[agencies]);const currentEmployee={id:'employee-demo',name:'Sarah Johnson'};
const duplicateCheck:Store['duplicateCheck']=input=>agencies.map(agency=>{let score=0;const reasons:string[]=[];if(normalize(input.name)&&normalize(agency.name)===normalize(input.name)){score+=60;reasons.push('Exact company name')}else if(normalize(input.name)&&normalize(agency.name).includes(normalize(input.name))){score+=30;reasons.push('Similar company name')}if(input.website&&normalize(agency.website)===normalize(input.website)){score+=80;reasons.push('Matching website')}if(input.phone&&normalize(agency.phone)===normalize(input.phone)){score+=80;reasons.push('Matching phone')}const email=input.generalEmail.trim().toLowerCase();if(email&&agency.generalEmail?.trim().toLowerCase()===email){score+=100;reasons.push('Matching agency email')}if(email&&agency.contacts.some(c=>c.email.trim().toLowerCase()===email)){score+=100;reasons.push('Email already belongs to a contact')}const emailDomain=email.split('@')[1]||'';const agencyDomain=agency.website.toLowerCase().replace(/^https?:\/\/(www\.)?/,'').split('/')[0];if(emailDomain&&agencyDomain&&emailDomain===agencyDomain){score+=20;reasons.push('Email domain matches website')}return {agency,score,reasons}}).filter(x=>x.score>=30).sort((a,b)=>b.score-a.score);
const createAgency:Store['createAgency']=input=>{const createdAt=new Date().toISOString();const agency:Agency={...input,id:crypto.randomUUID(),createdAt,contacts:[],activities:[],ownerEmployeeId:currentEmployee.id,ownerEmployeeName:currentEmployee.name,ownershipStartedAt:createdAt,ownershipExpiresAt:new Date(Date.now()+86400000*30).toISOString(),status:'new'};setAgencies(s=>[agency,...s]);return agency};
const addContact=(agencyId:string,input:Omit<AgencyContact,'id'>)=>setAgencies(s=>s.map(a=>a.id===agencyId?{...a,contacts:[...a.contacts,{...input,id:crypto.randomUUID()}],status:a.status==='new'?'researching':a.status}:a));
const addActivity=(agencyId:string,input:Omit<AgencyActivity,'id'|'occurredAt'>)=>setAgencies(s=>s.map(a=>a.id===agencyId?{...a,status:statusFromDisposition(input.disposition,Boolean(input.followUpAt)),ownershipExpiresAt:new Date(Date.now()+86400000*30).toISOString(),activities:[{...input,id:crypto.randomUUID(),occurredAt:new Date().toISOString()},...a.activities]}:a));
const completeFollowUp=(agencyId:string,activityId:string)=>setAgencies(s=>s.map(a=>a.id===agencyId?{...a,status:'contacting',activities:a.activities.map(x=>x.id===activityId?{...x,completedAt:new Date().toISOString()}:x)}:a));
const snoozeFollowUp=(agencyId:string,activityId:string,nextDate:string)=>setAgencies(s=>s.map(a=>a.id===agencyId?{...a,status:'follow_up_due',activities:a.activities.map(x=>x.id===activityId?{...x,followUpAt:nextDate,completedAt:undefined}:x)}:a));
const reassign=(agencyId:string,name:string)=>setAgencies(s=>s.map(a=>a.id===agencyId?{...a,ownerEmployeeId:crypto.randomUUID(),ownerEmployeeName:name,ownershipStartedAt:new Date().toISOString(),ownershipExpiresAt:new Date(Date.now()+86400000*30).toISOString()}:a));
const release=(agencyId:string)=>setAgencies(s=>s.map(a=>a.id===agencyId?{...a,ownerEmployeeId:'',ownerEmployeeName:'Unassigned',ownershipExpiresAt:new Date().toISOString()}:a));
const value=useMemo<Store>(()=>({agencies,currentEmployee,duplicateCheck,createAgency,addContact,addActivity,completeFollowUp,snoozeFollowUp,reassign,release,get:id=>agencies.find(a=>a.id===id)}),[agencies]);return <Context.Provider value={value}>{children}</Context.Provider>}
export function useAgencyStore(){const x=useContext(Context);if(!x)throw new Error('AgencyProvider missing');return x}
