-- RC1.2 Live Location Engine
-- One responsibility: persist and authorize Guard GPS without changing Presence, Mission, Dispatch, or Reporting state.
begin;

create table if not exists public.guard_location_history (
  id bigint generated by default as identity primary key,
  guard_id uuid not null references public.guards(id) on delete cascade,
  agency_id uuid not null references public.agencies(id) on delete cascade,
  job_id uuid null references public.marketplace_jobs(id) on delete set null,
  latitude double precision not null,
  longitude double precision not null,
  accuracy_meters double precision null,
  heading_degrees double precision null,
  speed_mps double precision null,
  recorded_at timestamptz not null default now(),
  constraint guard_location_latitude_check check (latitude between -90 and 90),
  constraint guard_location_longitude_check check (longitude between -180 and 180),
  constraint guard_location_accuracy_check check (accuracy_meters is null or accuracy_meters >= 0),
  constraint guard_location_heading_check check (heading_degrees is null or heading_degrees between 0 and 360),
  constraint guard_location_speed_check check (speed_mps is null or speed_mps >= 0)
);

create index if not exists guard_location_history_guard_recorded_idx
  on public.guard_location_history(guard_id, recorded_at desc);
create index if not exists guard_location_history_job_recorded_idx
  on public.guard_location_history(job_id, recorded_at asc)
  where job_id is not null;

alter table public.guard_location_history enable row level security;

create or replace function public.publish_guard_location_rc12(
  p_latitude double precision,
  p_longitude double precision,
  p_accuracy_meters double precision default null,
  p_heading_degrees double precision default null,
  p_speed_mps double precision default null
)
returns jsonb
language plpgsql
security definer
set search_path=public
set row_security=off
as $$
declare
  v_guard public.guards;
  v_job_id uuid;
  v_recorded_at timestamptz := now();
begin
  if p_latitude is null or p_latitude not between -90 and 90 then
    raise exception 'INVALID_LATITUDE' using errcode='22023';
  end if;
  if p_longitude is null or p_longitude not between -180 and 180 then
    raise exception 'INVALID_LONGITUDE' using errcode='22023';
  end if;

  select * into v_guard
  from public.guards
  where user_id=auth.uid()
  for update;

  if v_guard.id is null then
    raise exception 'GUARD_PROFILE_NOT_FOUND' using errcode='42501';
  end if;
  if v_guard.availability='offline' then
    raise exception 'GUARD_MUST_BE_ONLINE' using errcode='22023';
  end if;

  select ja.job_id into v_job_id
  from public.job_assignments ja
  where ja.guard_id=v_guard.id
    and ja.status in ('accepted','en_route','arrived','active')
  order by ja.assigned_at desc
  limit 1;

  update public.guards
     set current_latitude=p_latitude,
         current_longitude=p_longitude,
         last_location_at=v_recorded_at
   where id=v_guard.id;

  insert into public.guard_location_history(
    guard_id,agency_id,job_id,latitude,longitude,accuracy_meters,heading_degrees,speed_mps,recorded_at
  ) values (
    v_guard.id,v_guard.agency_id,v_job_id,p_latitude,p_longitude,p_accuracy_meters,p_heading_degrees,p_speed_mps,v_recorded_at
  );

  return jsonb_build_object(
    'success',true,
    'guard_id',v_guard.id,
    'agency_id',v_guard.agency_id,
    'job_id',v_job_id,
    'latitude',p_latitude,
    'longitude',p_longitude,
    'recorded_at',v_recorded_at
  );
end;
$$;

create or replace function public.get_agency_live_locations_rc12()
returns jsonb
language plpgsql
security definer
set search_path=public
set row_security=off
as $$
declare
  v_agency_id uuid;
  v_now timestamptz := now();
begin
  select am.agency_id into v_agency_id
  from public.agency_members am
  where am.user_id=auth.uid() and am.is_active=true
  limit 1;

  if v_agency_id is null then
    raise exception 'AGENCY_MEMBERSHIP_REQUIRED' using errcode='42501';
  end if;

  return coalesce((
    select jsonb_agg(jsonb_build_object(
      'guard_id',g.id,
      'name',coalesce(p.full_name,'Guard'),
      'availability',g.availability,
      'latitude',g.current_latitude,
      'longitude',g.current_longitude,
      'last_location_at',g.last_location_at,
      'freshness',case
        when g.availability='offline' then 'offline'
        when g.last_location_at is null then 'waiting'
        when g.last_location_at >= v_now-interval '2 minutes' then 'live'
        when g.last_location_at >= v_now-interval '10 minutes' then 'stale'
        else 'expired'
      end
    ) order by p.full_name)
    from public.guards g
    join public.profiles p on p.id=g.user_id
    where g.agency_id=v_agency_id
  ),'[]'::jsonb);
end;
$$;

create or replace function public.get_platform_live_locations_rc12()
returns jsonb
language plpgsql
security definer
set search_path=public
set row_security=off
as $$
declare
  v_now timestamptz := now();
begin
  if public.current_role() is distinct from 'platform_admin'::public.app_role then
    raise exception 'PLATFORM_ADMIN_REQUIRED' using errcode='42501';
  end if;
  return coalesce((
    select jsonb_agg(jsonb_build_object(
      'guard_id',g.id,'name',coalesce(p.full_name,'Guard'),'agency_id',g.agency_id,'agency_name',a.name,
      'availability',g.availability,'latitude',g.current_latitude,'longitude',g.current_longitude,
      'last_location_at',g.last_location_at,
      'freshness',case when g.availability='offline' then 'offline' when g.last_location_at is null then 'waiting'
        when g.last_location_at >= v_now-interval '2 minutes' then 'live'
        when g.last_location_at >= v_now-interval '10 minutes' then 'stale' else 'expired' end
    ) order by a.name,p.full_name)
    from public.guards g join public.agencies a on a.id=g.agency_id join public.profiles p on p.id=g.user_id
  ),'[]'::jsonb);
end;
$$;

create or replace function public.get_mission_route_history_rc12(p_job_id uuid)
returns jsonb
language plpgsql
security definer
set search_path=public
set row_security=off
as $$
declare
  v_role public.app_role;
  v_allowed boolean := false;
begin
  v_role := public.current_role();
  if v_role='platform_admin' then v_allowed:=true;
  elsif v_role='agency_admin' then
    select exists(select 1 from public.job_assignments ja join public.agency_members am on am.agency_id=ja.agency_id and am.user_id=auth.uid() and am.is_active=true where ja.job_id=p_job_id) into v_allowed;
  elsif v_role='guard' then
    select exists(select 1 from public.job_assignments ja join public.guards g on g.id=ja.guard_id and g.user_id=auth.uid() where ja.job_id=p_job_id) into v_allowed;
  end if;
  if not v_allowed then raise exception 'ROUTE_ACCESS_DENIED' using errcode='42501'; end if;
  return coalesce((select jsonb_agg(jsonb_build_object(
    'latitude',h.latitude,'longitude',h.longitude,'accuracy_meters',h.accuracy_meters,
    'heading_degrees',h.heading_degrees,'speed_mps',h.speed_mps,'recorded_at',h.recorded_at
  ) order by h.recorded_at) from public.guard_location_history h where h.job_id=p_job_id),'[]'::jsonb);
end;
$$;

revoke all on function public.publish_guard_location_rc12(double precision,double precision,double precision,double precision,double precision) from public;
revoke all on function public.get_agency_live_locations_rc12() from public;
revoke all on function public.get_platform_live_locations_rc12() from public;
revoke all on function public.get_mission_route_history_rc12(uuid) from public;
grant execute on function public.publish_guard_location_rc12(double precision,double precision,double precision,double precision,double precision) to authenticated;
grant execute on function public.get_agency_live_locations_rc12() to authenticated;
grant execute on function public.get_platform_live_locations_rc12() to authenticated;
grant execute on function public.get_mission_route_history_rc12(uuid) to authenticated;

commit;
