import { supabase } from '../../lib/supabase'

export type LocationFreshness='none'|'live'|'stale'|'expired'
export type GuardLiveLocation={guard_id:string;name:string;availability:string;latitude:number|null;longitude:number|null;last_location_at:string|null;freshness:LocationFreshness;job_id:string|null;mission_state:string|null}
export type ClientLiveLocation={job_id:string;title:string;property_name:string;property_address:string;property_latitude:number|null;property_longitude:number|null;guard_id:string;guard_name:string;availability:string;latitude:number|null;longitude:number|null;last_location_at:string|null;freshness:LocationFreshness;mission_state:string|null}|null
function db(){if(!supabase)throw new Error('Supabase is not configured.');return supabase}
export async function publishGuardLocation(position:GeolocationPosition){const c=position.coords;const {data,error}=await db().rpc('update_guard_location',{p_latitude:c.latitude,p_longitude:c.longitude,p_accuracy_meters:c.accuracy??null,p_heading_degrees:c.heading??null,p_speed_mps:c.speed??null,p_source:'browser'});if(error)throw new Error(error.message);return data}
export async function getAgencyLiveLocations(){const {data,error}=await db().rpc('get_agency_live_locations');if(error)throw new Error(error.message);return (data??[]) as GuardLiveLocation[]}
export async function getClientLiveLocation(){const {data,error}=await db().rpc('get_client_live_location');if(error)throw new Error(error.message);return (data??null) as ClientLiveLocation}
export function subscribeToLocationChanges(onChange:()=>void){if(!supabase)return()=>undefined;const channel=supabase.channel(`live-location-${crypto.randomUUID()}`).on('postgres_changes',{event:'*',schema:'public',table:'guards'},onChange).on('postgres_changes',{event:'INSERT',schema:'public',table:'guard_location_events'},onChange).subscribe();return()=>{void supabase?.removeChannel(channel)}}
export function startGuardLocationPublisher(input:{enabled:boolean;onPublished?:()=>void;onError?:(message:string)=>void}){if(!input.enabled||!navigator.geolocation)return()=>undefined;let lastSent=0;let lastLat:number|undefined;let lastLng:number|undefined;const watch=navigator.geolocation.watchPosition(async position=>{const now=Date.now();const moved=lastLat==null||Math.abs(position.coords.latitude-lastLat)>0.00008||Math.abs(position.coords.longitude-lastLng!)>0.00008;if(!moved&&now-lastSent<15000)return;try{await publishGuardLocation(position);lastSent=now;lastLat=position.coords.latitude;lastLng=position.coords.longitude;input.onPublished?.()}catch(e){input.onError?.(e instanceof Error?e.message:'Unable to publish location')}},error=>input.onError?.(error.message),{enableHighAccuracy:true,maximumAge:5000,timeout:12000});return()=>navigator.geolocation.clearWatch(watch)}
export const writeGuardLocation = publishGuardLocation
export const subscribeToLiveLocations = subscribeToLocationChanges
export const writeGuardLocation = publishGuardLocation
export const subscribeToLiveLocations = subscribeToLocationChanges
