import { useEffect,useRef } from 'react'
import { loadGoogleMaps } from './addressSearch'
import type { MissionMapMarker } from './MissionMap'
import type {ActiveMissionRoute,MissionRouteResult} from './missionRouting'
type Props={markers:MissionMapMarker[];focusTarget?:{latitude:number;longitude:number}|null;activeMissionRoute?:ActiveMissionRoute|null;onRouteUpdate?:(route:MissionRouteResult|null)=>void;onMarkerClick?:(marker:MissionMapMarker)=>void}
const HOME={lat:27.9506,lng:-82.4572,altitude:80}
export default function PlatformEarthMap({markers,focusTarget,activeMissionRoute,onRouteUpdate,onMarkerClick}:Props){
 const hostRef=useRef<HTMLDivElement|null>(null),mapRef=useRef<any>(null),markerEls=useRef<any[]>([]),boundaryEls=useRef<any[]>([]),routeEls=useRef<any[]>([]),pulseEls=useRef<any[]>([]),pulseTimer=useRef<number|null>(null),steadyRef=useRef(false),pending=useRef(focusTarget),markersRef=useRef(markers),clickRef=useRef(onMarkerClick);markersRef.current=markers;clickRef.current=onMarkerClick;pending.current=focusTarget
 const fly=(target:{latitude:number;longitude:number})=>{const map=mapRef.current;if(!map||!steadyRef.current){pending.current=target;return}pending.current=null;map.stopCameraAnimation?.();const c=map.center,currentLat=Number(c?.lat??HOME.lat),currentLng=Number(c?.lng??HOME.lng),dLat=(target.latitude-currentLat)*Math.PI/180,dLng=(target.longitude-currentLng)*Math.PI/180,a=Math.sin(dLat/2)**2+Math.cos(currentLat*Math.PI/180)*Math.cos(target.latitude*Math.PI/180)*Math.sin(dLng/2)**2,miles=3958.8*2*Math.asin(Math.sqrt(a)),duration=Math.round(Math.min(14000,Math.max(3200,3200+miles*3)));map.flyCameraTo({endCamera:{center:{lat:target.latitude,lng:target.longitude,altitude:35},range:950,tilt:55,heading:0},durationMillis:duration})}
 const renderMarkers=async()=>{const map=mapRef.current;if(!map)return;const google=await loadGoogleMaps(),maps3d=await google.maps.importLibrary('maps3d');markerEls.current.forEach(el=>el.remove());pulseEls.current.forEach((item:any)=>item.el?.remove());markerEls.current=[];pulseEls.current=[];if(pulseTimer.current){window.clearInterval(pulseTimer.current);pulseTimer.current=null}const Marker=maps3d.Marker3DInteractiveElement??maps3d.Marker3DElement,Polyline=maps3d.Polyline3DElement,opportunities:MissionMapMarker[]=[];markersRef.current.forEach(marker=>{const isOpportunity=['job','priority','emergency'].includes(String(marker.type))&&String(marker.id).startsWith('job-'),el=new Marker({position:{lat:marker.latitude,lng:marker.longitude,altitude:isOpportunity?125:80},label:isOpportunity?'AVAILABLE JOB':marker.label||marker.title||'',sizePreserved:true,extruded:marker.type==='guard'});el.addEventListener?.('gmp-click',()=>{fly({latitude:marker.latitude,longitude:marker.longitude});clickRef.current?.(marker)});map.append(el);markerEls.current.push(el);if(isOpportunity)opportunities.push(marker)});if(Polyline&&opportunities.length){let tick=0;const circle=(m:MissionMapMarker,radius:number)=>Array.from({length:49},(_,i)=>{const a=i/48*Math.PI*2,lat=m.latitude+(radius/111320)*Math.cos(a),lng=m.longitude+(radius/(111320*Math.cos(m.latitude*Math.PI/180)))*Math.sin(a);return{lat,lng,altitude:105}});opportunities.forEach(m=>{for(let ring=0;ring<3;ring++){const el=new Polyline({coordinates:circle(m,80+ring*70),strokeColor:ring===0?'#ffffff':'#ff2d2d',strokeWidth:ring===0?7:5,altitudeMode:'ABSOLUTE',drawsOccludedSegments:true});map.append(el);pulseEls.current.push({el,m,ring})}});pulseTimer.current=window.setInterval(()=>{tick=(tick+1)%90;pulseEls.current.forEach((item:any)=>{const phase=(tick+item.ring*30)%90/90,radius=70+phase*430,alpha=Math.max(.12,1-phase);item.el.coordinates=circle(item.m,radius);item.el.strokeColor=item.ring===0?`rgba(255,255,255,${alpha})`:`rgba(255,45,45,${alpha})`;item.el.strokeWidth=Math.max(2,8-phase*5)})},55)}}
 const renderBoundaries=async()=>{const map=mapRef.current;if(!map)return;const google=await loadGoogleMaps(),maps3d=await google.maps.importLibrary('maps3d');const Polyline=maps3d.Polyline3DElement;if(!Polyline)return;const data=await fetch('/maps/us-states-boundaries.geojson').then(r=>r.json());boundaryEls.current.forEach(el=>el.remove());boundaryEls.current=[];for(const feature of data.features??[]){const geometry=feature.geometry;if(!geometry)continue;const polygons=geometry.type==='Polygon'?[geometry.coordinates]:geometry.type==='MultiPolygon'?geometry.coordinates:[];for(const polygon of polygons){for(const ring of polygon){const el=new Polyline({coordinates:ring.map(([lng,lat]:number[])=>({lat,lng,altitude:160})),strokeColor:'#ffffff',strokeWidth:3,altitudeMode:'ABSOLUTE',drawsOccludedSegments:false});map.append(el);boundaryEls.current.push(el)}}}}
 useEffect(()=>{let cancelled=false;void(async()=>{const google=await loadGoogleMaps(),maps3d=await google.maps.importLibrary('maps3d');if(cancelled||!hostRef.current)return;const{Map3DElement}=maps3d,map=new Map3DElement({center:HOME,range:6500,tilt:65,heading:0,mode:'HYBRID',gestureHandling:'COOPERATIVE',defaultUIHidden:true});map.style.width='100%';map.style.height='100%';hostRef.current.replaceChildren(map);mapRef.current=map;await Promise.all([renderMarkers(),renderBoundaries()]);map.addEventListener('gmp-steadychange',(e:any)=>{steadyRef.current=Boolean(e?.isSteady);if(steadyRef.current&&pending.current)fly(pending.current)})})().catch(console.error);return()=>{cancelled=true;steadyRef.current=false;if(pulseTimer.current)window.clearInterval(pulseTimer.current);pulseTimer.current=null;pulseEls.current.forEach((item:any)=>item.el?.remove());pulseEls.current=[];mapRef.current?.stopCameraAnimation?.();mapRef.current=null}},[])
 useEffect(()=>{void renderMarkers().catch(console.error)},[markers])
 useEffect(()=>{let cancelled=false;const clear=()=>{routeEls.current.forEach(el=>el.remove());routeEls.current=[];onRouteUpdate?.(null)};void(async()=>{clear();const map=mapRef.current,route=activeMissionRoute;if(!map||!route)return;const google=await loadGoogleMaps(),result=await new google.maps.DirectionsService().route({origin:{lat:route.assignedGuard.latitude,lng:route.assignedGuard.longitude},destination:{lat:route.destination.latitude,lng:route.destination.longitude},travelMode:google.maps.TravelMode.DRIVING,drivingOptions:{departureTime:new Date(),trafficModel:google.maps.TrafficModel.BEST_GUESS}});if(cancelled)return;const best=result.routes?.[0],path=best?.overview_path??[];if(!path.length)return;const maps3d=await google.maps.importLibrary('maps3d'),Polyline=maps3d.Polyline3DElement;if(!Polyline||cancelled)return;const coordinates=path.map((p:any)=>({lat:p.lat(),lng:p.lng(),altitude:95}));const glow=new Polyline({coordinates,strokeColor:'#18a7ff',strokeWidth:16,altitudeMode:'ABSOLUTE',drawsOccludedSegments:true}),line=new Polyline({coordinates,strokeColor:'#20d4ff',strokeWidth:6,altitudeMode:'ABSOLUTE',drawsOccludedSegments:true});map.append(glow);map.append(line);routeEls.current=[glow,line];const legs=best?.legs??[],distanceMeters=legs.reduce((n:number,l:any)=>n+(l.distance?.value??0),0),durationSeconds=legs.reduce((n:number,l:any)=>n+(l.duration_in_traffic?.value??l.duration?.value??0),0);onRouteUpdate?.({distanceMeters,durationSeconds,distanceText:legs.map((l:any)=>l.distance?.text).filter(Boolean).join(' + '),durationText:legs.map((l:any)=>(l.duration_in_traffic??l.duration)?.text).filter(Boolean).join(' + ')})})().catch(err=>{console.error(err);clear()});return()=>{cancelled=true;routeEls.current.forEach(el=>el.remove());routeEls.current=[]}},[activeMissionRoute?.missionId,activeMissionRoute?.assignedGuard.latitude,activeMissionRoute?.assignedGuard.longitude,activeMissionRoute?.destination.latitude,activeMissionRoute?.destination.longitude])
 useEffect(()=>{if(focusTarget)fly(focusTarget)},[focusTarget?.latitude,focusTarget?.longitude])
 const zoom=(direction:'in'|'out')=>{const map=mapRef.current;if(!map)return;map.stopCameraAnimation?.();const current=Number(map.range)||8500;map.range=direction==='in'?Math.max(300,current*.58):Math.min(30000000,current*1.72)}
 const reset=()=>{const map=mapRef.current;if(!map)return;map.stopCameraAnimation?.();map.center=HOME;map.range=6500;map.tilt=65;map.heading=0}
 return <div className="platform-earth-map"><div ref={hostRef} className="platform-earth-canvas" aria-label="Live Google Earth platform map"/><div className="platform-earth-controls" aria-label="Map controls"><button type="button" onClick={()=>zoom('in')} aria-label="Zoom in">+</button><button type="button" onClick={()=>zoom('out')} aria-label="Zoom out">−</button><button type="button" className="platform-earth-reset" onClick={reset} aria-label="Reset map">⌂</button></div></div>
}
