import { useEffect,useRef } from 'react'
import { loadGoogleMaps } from './addressSearch'
import type { MissionMapMarker } from './MissionMap'
type Props={markers:MissionMapMarker[];focusTarget?:{latitude:number;longitude:number}|null}
const HOME={lat:27.9506,lng:-82.4572,altitude:80}
export default function PlatformEarthMap({markers,focusTarget}:Props){
 const hostRef=useRef<HTMLDivElement|null>(null),mapRef=useRef<any>(null),markerEls=useRef<any[]>([]),boundaryEls=useRef<any[]>([]),steadyRef=useRef(false),pending=useRef(focusTarget),markersRef=useRef(markers);markersRef.current=markers;pending.current=focusTarget
 const fly=(target:{latitude:number;longitude:number})=>{const map=mapRef.current;if(!map||!steadyRef.current){pending.current=target;return}pending.current=null;map.stopCameraAnimation?.();const c=map.center,currentLat=Number(c?.lat??HOME.lat),currentLng=Number(c?.lng??HOME.lng),dLat=(target.latitude-currentLat)*Math.PI/180,dLng=(target.longitude-currentLng)*Math.PI/180,a=Math.sin(dLat/2)**2+Math.cos(currentLat*Math.PI/180)*Math.cos(target.latitude*Math.PI/180)*Math.sin(dLng/2)**2,miles=3958.8*2*Math.asin(Math.sqrt(a)),duration=Math.round(Math.min(14000,Math.max(3200,3200+miles*3)));map.flyCameraTo({endCamera:{center:{lat:target.latitude,lng:target.longitude,altitude:35},range:950,tilt:55,heading:0},durationMillis:duration})}
 const renderMarkers=async()=>{const map=mapRef.current;if(!map)return;const google=await loadGoogleMaps(),maps3d=await google.maps.importLibrary('maps3d');markerEls.current.forEach(el=>el.remove());markerEls.current=[];const Marker=maps3d.Marker3DInteractiveElement??maps3d.Marker3DElement;markersRef.current.forEach(marker=>{const el=new Marker({position:{lat:marker.latitude,lng:marker.longitude,altitude:80},label:marker.label||marker.title||'',sizePreserved:true,extruded:marker.type==='guard'});el.addEventListener?.('gmp-click',()=>fly({latitude:marker.latitude,longitude:marker.longitude}));map.append(el);markerEls.current.push(el)})}
 const renderBoundaries=async()=>{const map=mapRef.current;if(!map)return;const google=await loadGoogleMaps(),maps3d=await google.maps.importLibrary('maps3d');const Polyline=maps3d.Polyline3DElement;if(!Polyline)return;const data=await fetch('/maps/us-states-boundaries.geojson').then(r=>r.json());boundaryEls.current.forEach(el=>el.remove());boundaryEls.current=[];for(const feature of data.features??[]){const geometry=feature.geometry;if(!geometry)continue;const polygons=geometry.type==='Polygon'?[geometry.coordinates]:geometry.type==='MultiPolygon'?geometry.coordinates:[];for(const polygon of polygons){for(const ring of polygon){const el=new Polyline({coordinates:ring.map(([lng,lat]:number[])=>({lat,lng,altitude:160})),strokeColor:'#ffffff',strokeWidth:3,altitudeMode:'ABSOLUTE',drawsOccludedSegments:false});map.append(el);boundaryEls.current.push(el)}}}}
 useEffect(()=>{let cancelled=false;void(async()=>{const google=await loadGoogleMaps(),maps3d=await google.maps.importLibrary('maps3d');if(cancelled||!hostRef.current)return;const{Map3DElement}=maps3d,map=new Map3DElement({center:HOME,range:6500,tilt:65,heading:0,mode:'HYBRID',gestureHandling:'COOPERATIVE',defaultUIHidden:true});map.style.width='100%';map.style.height='100%';hostRef.current.replaceChildren(map);mapRef.current=map;await Promise.all([renderMarkers(),renderBoundaries()]);map.addEventListener('gmp-steadychange',(e:any)=>{steadyRef.current=Boolean(e?.isSteady);if(steadyRef.current&&pending.current)fly(pending.current)})})().catch(console.error);return()=>{cancelled=true;steadyRef.current=false;mapRef.current?.stopCameraAnimation?.();mapRef.current=null}},[])
 useEffect(()=>{void renderMarkers().catch(console.error)},[markers])
 useEffect(()=>{if(focusTarget)fly(focusTarget)},[focusTarget?.latitude,focusTarget?.longitude])
 const zoom=(direction:'in'|'out')=>{const map=mapRef.current;if(!map)return;map.stopCameraAnimation?.();const current=Number(map.range)||8500;map.range=direction==='in'?Math.max(300,current*.58):Math.min(30000000,current*1.72)}
 const reset=()=>{const map=mapRef.current;if(!map)return;map.stopCameraAnimation?.();map.center=HOME;map.range=6500;map.tilt=65;map.heading=0}
 return <div className="platform-earth-map"><div ref={hostRef} className="platform-earth-canvas" aria-label="Live Google Earth platform map"/><div className="platform-earth-controls" aria-label="Map controls"><button type="button" onClick={()=>zoom('in')} aria-label="Zoom in">+</button><button type="button" onClick={()=>zoom('out')} aria-label="Zoom out">−</button><button type="button" className="platform-earth-reset" onClick={reset} aria-label="Reset map">⌂</button></div></div>
}
