import { supabase } from '../../lib/supabase'
import type { ClientJob,ClientPaymentProfile,ClientProperty,JobEstimate } from '../client/clientRepository'
import type { MarketplaceJobRow,AgencyWorkspace } from '../marketplace/marketplaceRepository'

export type DeveloperLiveAccounts={clients:Array<{id:string;user_id:string;name:string;email:string|null}>;agencies:Array<{id:string;name:string;status:string}>;guards:Array<{id:string;user_id:string;agency_id:string;name:string;availability:string}>}
function db(){if(!supabase)throw new Error('Supabase is not configured.');return supabase}
export async function getDeveloperLiveAccounts(){const{data,error}=await db().rpc('get_developer_live_accounts_rc1');if(error)throw new Error(error.message);return data as DeveloperLiveAccounts}
export async function getDeveloperClientWorkspace(clientId:string){const{data,error}=await db().rpc('get_developer_client_workspace_rc1',{p_client_id:clientId});if(error)throw new Error(error.message);const x=data as any;return{clientId:String(x.client_id),properties:(x.properties??[]) as ClientProperty[],jobs:(x.jobs??[]) as ClientJob[],paymentProfile:(x.payment_profile??null) as ClientPaymentProfile|null}}
export async function getDeveloperJobEstimate(input:{propertyId:string;serviceType:string;priority:'standard'|'priority'|'emergency';durationMinutes:number;scheduledFor:string|null;requestedStart?:string;vacationStartDate?:string|null;vacationEndDate?:string|null;vacationChecksPerDay?:number|null;guardCount?:number}){const{data,error}=await db().rpc('get_developer_job_estimate_rc1',{p_property_id:input.propertyId,p_service_type:input.serviceType,p_priority:input.priority,p_duration_minutes:input.durationMinutes,p_scheduled_for:input.scheduledFor?new Date(input.scheduledFor).toISOString():null,p_requested_start:input.requestedStart||'scheduled',p_vacation_start_date:input.vacationStartDate||null,p_vacation_end_date:input.vacationEndDate||null,p_vacation_checks_per_day:input.vacationChecksPerDay||null,p_guard_count:input.guardCount||1});if(error)throw new Error(error.message);return data as JobEstimate}
export async function createDeveloperTestJob(input:{clientId:string;propertyId:string;title:string;instructions:string;priority:'standard'|'priority'|'emergency';scheduledFor:string|null;durationMinutes:number;serviceType:string;requestedStart:string;contactPhone:string;accessNotes:string;vacationStartDate?:string|null;vacationEndDate?:string|null;vacationChecksPerDay?:number|null;guardCount?:number}){const{data,error}=await db().rpc('create_developer_test_job_rc1',{p_client_id:input.clientId,p_property_id:input.propertyId,p_title:input.title.trim(),p_instructions:input.instructions.trim()||null,p_priority:input.priority,p_scheduled_for:input.scheduledFor?new Date(input.scheduledFor).toISOString():null,p_duration_minutes:input.durationMinutes,p_service_type:input.serviceType,p_requested_start:input.requestedStart,p_client_contact_phone:input.contactPhone||null,p_access_notes:input.accessNotes||null,p_vacation_start_date:input.vacationStartDate||null,p_vacation_end_date:input.vacationEndDate||null,p_vacation_checks_per_day:input.vacationChecksPerDay||null,p_guard_count:input.guardCount||1});if(error)throw new Error(error.message);return{id:data as string}}
export async function getDeveloperAgencyWorkspace(agencyId:string):Promise<AgencyWorkspace>{const client=db();const[{data:agency,error:ae},{data:rows,error:je}]=await Promise.all([client.from('agencies').select('id,name,status').eq('id',agencyId).single(),client.from('marketplace_jobs').select('id,title,instructions,status,priority,accepted_agency_id,accepted_at,scheduled_for,duration_minutes,payout_cents,estimated_total_cents,platform_fee_cents,agency_payout_cents,payment_status,payout_status,payout_hold_reason,service_type,requested_start,required_guards,created_at,updated_at,property:properties(name,address,latitude,longitude,photo_url),client:clients(display_name)').or(`status.eq.open,accepted_agency_id.eq.${agencyId}`).order('created_at',{ascending:false})]);if(ae)throw new Error(ae.message);if(je)throw new Error(je.message);const jobs=(rows??[]) as unknown as MarketplaceJobRow[];return{agencyId,name:agency.name,status:agency.status,open:jobs.filter(j=>j.status==='open'&&['authorized','captured'].includes(String(j.payment_status))),claimed:jobs.filter(j=>j.accepted_agency_id===agencyId&&!['open','completed','cancelled'].includes(j.status))}}
export async function claimDeveloperTestJob(jobId:string,agencyId:string){const{data,error}=await db().rpc('claim_developer_test_job_rc1',{p_job_id:jobId,p_agency_id:agencyId});if(error)throw new Error(error.message);return data as {accepted:boolean;reason?:string}}
export async function getDeveloperAgencyGuards(agencyId:string){const{data,error}=await db().from('guards').select('id,user_id,agency_id,availability,current_latitude,current_longitude,last_location_at,profile:profiles!guards_user_id_fkey(full_name)').eq('agency_id',agencyId);if(error)throw new Error(error.message);return(data??[]).map((g:any)=>({id:g.id,user_id:g.user_id,agency_id:g.agency_id,name:g.profile?.full_name||'Guard',availability:g.availability,latitude:g.current_latitude==null?null:Number(g.current_latitude),longitude:g.current_longitude==null?null:Number(g.current_longitude),last_location_at:g.last_location_at}))}

export async function setDeveloperGuardPresence(guardId:string,online:boolean,latitude?:number|null,longitude?:number|null){const{data,error}=await db().rpc('set_developer_guard_presence_rc1',{p_guard_id:guardId,p_online:online,p_latitude:latitude??null,p_longitude:longitude??null});if(error)throw new Error(error.message);return data}
