import { supabase } from '../../lib/supabase'
import type { ClientJob,ClientPaymentProfile,ClientProperty,JobEstimate } from '../client/clientRepository'
import type { MarketplaceJobRow,AgencyWorkspace } from '../marketplace/marketplaceRepository'
import type { AgencyDispatchWorkspace } from '../dispatch/dispatchRepository'

export type DeveloperLiveAccounts={clients:Array<{id:string;user_id:string;name:string;email:string|null}>;agencies:Array<{id:string;name:string;status:string}>;guards:Array<{id:string;user_id:string;agency_id:string;name:string;availability:string}>}
function db(){if(!supabase)throw new Error('Supabase is not configured.');return supabase}
export async function getDeveloperLiveAccounts(){const{data,error}=await db().rpc('get_developer_live_accounts_rc1');if(error)throw new Error(error.message);return data as DeveloperLiveAccounts}
export async function getDeveloperClientWorkspace(clientId:string){const{data,error}=await db().rpc('get_developer_client_workspace_rc1',{p_client_id:clientId});if(error)throw new Error(error.message);const x=data as any;return{clientId:String(x.client_id),properties:(x.properties??[]) as ClientProperty[],jobs:(x.jobs??[]) as ClientJob[],paymentProfile:(x.payment_profile??null) as ClientPaymentProfile|null}}
export async function getDeveloperJobEstimate(input:{propertyId:string;serviceType:string;priority:'standard'|'priority'|'emergency';durationMinutes:number;scheduledFor:string|null;requestedStart?:string;vacationStartDate?:string|null;vacationEndDate?:string|null;vacationChecksPerDay?:number|null;guardCount?:number}){const{data,error}=await db().rpc('get_developer_job_estimate_rc1',{p_property_id:input.propertyId,p_service_type:input.serviceType,p_priority:input.priority,p_duration_minutes:input.durationMinutes,p_scheduled_for:input.scheduledFor?new Date(input.scheduledFor).toISOString():null,p_requested_start:input.requestedStart||'scheduled',p_vacation_start_date:input.vacationStartDate||null,p_vacation_end_date:input.vacationEndDate||null,p_vacation_checks_per_day:input.vacationChecksPerDay||null,p_guard_count:input.guardCount||1});if(error)throw new Error(error.message);return data as JobEstimate}
export async function createDeveloperTestJob(input:{clientId:string;propertyId:string;title:string;instructions:string;priority:'standard'|'priority'|'emergency';scheduledFor:string|null;durationMinutes:number;serviceType:string;requestedStart:string;contactPhone:string;accessNotes:string;vacationStartDate?:string|null;vacationEndDate?:string|null;vacationChecksPerDay?:number|null;guardCount?:number}){const{data,error}=await db().rpc('create_developer_test_job_rc1',{p_client_id:input.clientId,p_property_id:input.propertyId,p_title:input.title.trim(),p_instructions:input.instructions.trim()||null,p_priority:input.priority,p_scheduled_for:input.scheduledFor?new Date(input.scheduledFor).toISOString():null,p_duration_minutes:input.durationMinutes,p_service_type:input.serviceType,p_requested_start:input.requestedStart,p_client_contact_phone:input.contactPhone||null,p_access_notes:input.accessNotes||null,p_vacation_start_date:input.vacationStartDate||null,p_vacation_end_date:input.vacationEndDate||null,p_vacation_checks_per_day:input.vacationChecksPerDay||null,p_guard_count:input.guardCount||1});if(error)throw new Error(error.message);return{id:data as string}}
export async function getDeveloperAgencyContext(agencyId:string){const{data,error}=await db().rpc('get_developer_agency_workspace_rc2',{p_agency_id:agencyId});if(error)throw new Error(error.message);const x=data as any;const jobs=(x.jobs??[]) as MarketplaceJobRow[];return{workspace:{agencyId:String(x.agency.id),name:String(x.agency.name),status:String(x.agency.status),open:jobs.filter(j=>j.status==='open'&&['authorized','captured'].includes(String(j.payment_status))),claimed:jobs.filter(j=>j.accepted_agency_id===agencyId&&!['open','completed','cancelled'].includes(j.status))} as AgencyWorkspace,guards:(x.guards??[]) as Array<{id:string;user_id:string;agency_id:string;name:string;availability:string;latitude:number|null;longitude:number|null;last_location_at:string|null}>}}
export async function getDeveloperAgencyWorkspace(agencyId:string){return (await getDeveloperAgencyContext(agencyId)).workspace}
export async function claimDeveloperTestJob(jobId:string,agencyId:string){const{data,error}=await db().rpc('claim_developer_test_job_rc1',{p_job_id:jobId,p_agency_id:agencyId});if(error)throw new Error(error.message);return data as {accepted:boolean;reason?:string}}
export async function getDeveloperAgencyGuards(agencyId:string){return (await getDeveloperAgencyContext(agencyId)).guards}

export async function setDeveloperGuardPresence(guardId:string,online:boolean,latitude?:number|null,longitude?:number|null){const{data,error}=await db().rpc('set_developer_guard_presence_rc1',{p_guard_id:guardId,p_online:online,p_latitude:latitude??null,p_longitude:longitude??null});if(error)throw new Error(error.message);return data}

export async function getDeveloperAgencyDispatchWorkspace(agencyId:string):Promise<AgencyDispatchWorkspace>{const{data,error}=await db().rpc('get_developer_agency_dispatch_workspace_rc1',{p_agency_id:agencyId});if(error)throw new Error(error.message);return data as AgencyDispatchWorkspace}

export async function assignDeveloperGuard(jobId:string,agencyId:string,guardId:string){const{data,error}=await db().rpc('assign_developer_guard_rc1',{p_job_id:jobId,p_agency_id:agencyId,p_guard_id:guardId});if(error)throw new Error(error.message);return data as {success:boolean;job_id:string;guard_id:string;status:string}}
export async function getDeveloperGuardWorkspace(guardId:string){const{data,error}=await db().rpc('get_developer_guard_workspace_rc1',{p_guard_id:guardId});if(error)throw new Error(error.message);return data as {guard:{id:string;user_id:string;agency_id:string;availability:string;latitude:number|null;longitude:number|null;last_location_at:string|null};assignment:import('../dispatch/dispatchRepository').DispatchMission|null;events:import('../dispatch/dispatchRepository').DispatchEvent[]}}

export async function acceptDeveloperGuardAssignment(guardId:string,jobId:string,expectedVersion?:number){const{data,error}=await db().rpc('accept_developer_guard_assignment_rc1',{p_guard_id:guardId,p_job_id:jobId,p_expected_version:expectedVersion??null});if(error)throw new Error(error.message);return data}

export async function transitionDeveloperGuardMission(input:{guardId:string;jobId:string;action:'accept'|'start_route'|'mark_arrived'|'save_payload'|'complete_checkpoint'|'submit';expectedVersion?:number;checkpoint?:number;evidence?:unknown;incidents?:unknown}){const{data,error}=await db().rpc('transition_developer_guard_mission_rc1',{p_guard_id:input.guardId,p_job_id:input.jobId,p_action:input.action,p_expected_version:input.expectedVersion??null,p_checkpoint:input.checkpoint??null,p_evidence:input.evidence??null,p_incidents:input.incidents??null});if(error)throw new Error(error.message);return data}
