import { supabase } from '../../lib/supabase'
function db(){if(!supabase)throw new Error('Supabase is not configured.');return supabase}
export type AgencySettings={id:string;name:string;status:string;license_number:string|null;service_radius_miles:number;logo_url:string|null;website:string|null;public_phone:string|null;business_address:string|null;description:string|null;settings:Record<string,any>;payout_method?:string|null;payout_note?:string|null}
export async function getDeveloperAgencySettings(agencyId:string):Promise<AgencySettings>{const{data,error}=await db().rpc('get_developer_agency_settings_rc1',{p_agency_id:agencyId});if(error)throw new Error(error.message);return data as AgencySettings}
export async function getAgencySettings():Promise<AgencySettings>{const{data,error}=await db().rpc('get_my_agency_settings_rc1');if(error)throw new Error(error.message);return data as AgencySettings}
export async function saveAgencySettings(v:AgencySettings){const{data,error}=await db().rpc('update_my_agency_settings_rc1',{p_name:v.name,p_logo_url:v.logo_url,p_website:v.website,p_public_phone:v.public_phone,p_business_address:v.business_address,p_description:v.description,p_service_radius_miles:v.service_radius_miles,p_settings:v.settings??{}});if(error)throw new Error(error.message);return data as AgencySettings}
export async function uploadAgencyLogo(agencyId:string,file:File){if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Use a JPG, PNG or WebP logo.');if(file.size>5*1024*1024)throw new Error('Logo must be 5 MB or smaller.');const ext=file.name.split('.').pop()?.toLowerCase()||'jpg',path=`${agencyId}/logo-${Date.now()}.${ext}`,client=db();const{error}=await client.storage.from('agency-branding').upload(path,file,{contentType:file.type,upsert:false});if(error)throw new Error(error.message);return client.storage.from('agency-branding').getPublicUrl(path).data.publicUrl}
export type AgencyAccountCenter={profile:{user_id:string;full_name:string|null;phone:string|null;account_status:string;email:string;created_at:string};members:Array<{user_id:string;full_name:string;email:string;phone:string|null;role:string;is_active:boolean;created_at:string}>}
export async function getAgencyAccountCenter(){const{data,error}=await db().rpc('get_my_agency_account_center_rc1');if(error)throw new Error(error.message);return data as AgencyAccountCenter}
export async function updateMyAccountProfile(fullName:string,phone:string){const{data,error}=await db().rpc('update_my_account_profile_rc1',{p_full_name:fullName,p_phone:phone});if(error)throw new Error(error.message);return data}
export async function changeMyPassword(password:string){if(password.length<8)throw new Error('Password must be at least 8 characters.');const{error}=await db().auth.updateUser({password});if(error)throw new Error(error.message)}
export async function signOutOtherSessions(){const{error}=await db().auth.signOut({scope:'others'});if(error)throw new Error(error.message)}
export async function deactivateMyAgencyAccount(confirmation:string){const{data,error}=await db().rpc('deactivate_my_agency_account_rc1',{p_confirmation:confirmation});if(error)throw new Error(error.message);return data}
