import { useEffect, useMemo, useState, type ReactNode } from 'react'
import { AlertTriangle, CheckCircle2, Clock3, Crosshair, LoaderCircle, MapPin, Radio, RefreshCw, ShieldCheck, Siren, UserRoundCheck, Users, Zap } from 'lucide-react'
import AgencyOperationsMap from './modules/maps/AgencyOperationsMap'
import { assignGuard } from './modules/dispatch/dispatchRepository'
import { getAgencyOperationsCenter, subscribeToAgencyOperations, type AgencyOperationsWorkspace, type OperationsMission } from './modules/operations/agencyOperationsRepository'

type View='all'|'dispatch'|'active'|'emergency'|'completed'
const empty:AgencyOperationsWorkspace={agency:{id:'',name:'Agency'},generated_at:new Date().toISOString(),kpis:{total_guards:0,online_guards:0,available_guards:0,active_missions:0,awaiting_guard:0,emergencies:0,incidents:0},guards:[],missions:[],events:[]}

export default function AgencyOperationsCenter({preview=false,onMarketplace,onToast}:{preview?:boolean;onMarketplace:()=>void;onToast:(message:string)=>void}){
 const [workspace,setWorkspace]=useState<AgencyOperationsWorkspace>(empty)
 const [view,setView]=useState<View>('all')
 const [selectedId,setSelectedId]=useState<string|null>(null)
 const [loading,setLoading]=useState(!preview)
 const [error,setError]=useState<string|null>(null)
 const [assigning,setAssigning]=useState<string|null>(null)
 const load=async()=>{if(preview)return;setLoading(true);try{const next=await getAgencyOperationsCenter();setWorkspace(next);setSelectedId(current=>current&&next.missions.some(m=>m.job_id===current)?current:(next.missions.find(m=>!['completed','cancelled'].includes(m.state))?.job_id??next.missions[0]?.job_id??null));setError(null)}catch(cause){setError(cause instanceof Error?cause.message:'Operations Center unavailable.')}finally{setLoading(false)}}
 useEffect(()=>{void load();if(preview)return;return subscribeToAgencyOperations(()=>void load())},[preview])
 const missions=useMemo(()=>workspace.missions.filter(m=>view==='all'?m.state!=='cancelled':view==='dispatch'?m.state==='awaiting_guard'||m.state==='offered':view==='active'?['accepted','en_route','active','checkpoint','review'].includes(m.state):view==='emergency'?m.priority==='emergency'&&!['completed','cancelled'].includes(m.state):m.state==='completed'),[workspace.missions,view])
 const selected=workspace.missions.find(m=>m.job_id===selectedId)??missions[0]??null
 const activeMapMissions=missions.filter(m=>!['completed','cancelled'].includes(m.state))
 const available=workspace.guards.filter(g=>g.availability==='available')
 const assign=async(mission:OperationsMission,guardId:string)=>{setAssigning(mission.job_id);try{await assignGuard(mission.job_id,guardId);await load();onToast('Guard assignment entered the certified Mission Engine.')}catch(cause){onToast(cause instanceof Error?cause.message:'Unable to assign Guard.')}finally{setAssigning(null)}}
 return <section className="aoc-shell">
  <header className="aoc-header"><div><span className="eyebrow">RC3.0 · AGENCY OPERATIONS CENTER</span><h1>One command surface. One operational truth.</h1><p>Live guards, mission authority, dispatch, emergencies, incidents, and activity are projected from one database contract.</p></div><div className="aoc-header-actions"><button onClick={()=>void load()} disabled={loading}>{loading?<LoaderCircle className="spin"/>:<RefreshCw/>}Synchronize</button><button onClick={onMarketplace}><Crosshair/>Marketplace</button></div></header>
  {error&&<div className="aoc-error"><AlertTriangle/><div><strong>Operations authority unavailable</strong><span>{error}</span></div></div>}
  <div className="aoc-kpis"><Metric icon={<Users/>} label="Online Guards" value={workspace.kpis.online_guards} detail={`${workspace.kpis.available_guards} available`}/><Metric icon={<Radio/>} label="Active Missions" value={workspace.kpis.active_missions} detail={`${workspace.kpis.awaiting_guard} need dispatch`}/><Metric icon={<Siren/>} label="Emergencies" value={workspace.kpis.emergencies} detail="Immediate attention" danger={workspace.kpis.emergencies>0}/><Metric icon={<AlertTriangle/>} label="Open Incidents" value={workspace.kpis.incidents} detail="Mission audit trail" danger={workspace.kpis.incidents>0}/></div>
  <div className="aoc-tabs">{([['all','Live Board'],['dispatch','Dispatch Queue'],['active','In Motion'],['emergency','Emergency'],['completed','Completed']] as [View,string][]).map(([key,label])=><button key={key} className={view===key?'active':''} onClick={()=>setView(key)}>{label}<b>{countFor(key,workspace)}</b></button>)}</div>
  <div className="aoc-grid">
   <div className="aoc-map-panel"><AgencyOperationsMap jobs={activeMapMissions.map(m=>({id:m.job_id,title:m.title,kind:m.priority,latitude:m.property.latitude,longitude:m.property.longitude}))} guards={workspace.guards.map(g=>({id:g.id,name:g.name,status:g.availability==='on_mission'?'on-mission':g.availability,latitude:g.latitude,longitude:g.longitude,freshness:g.freshness}))} showJobs showGuards/><div className="aoc-map-status"><span><i className="live-dot"/>Live authority</span><small>Generated {new Date(workspace.generated_at).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}</small></div></div>
   <aside className="aoc-guard-rail"><div className="aoc-panel-head"><div><strong>GUARD STATUS</strong><small>{workspace.guards.length} rostered</small></div><span>{available.length} available</span></div><div className="aoc-guard-list">{workspace.guards.map(g=><article key={g.id} className={`aoc-guard ${g.availability}`}><div className="aoc-avatar">{g.name.split(' ').map(v=>v[0]).join('').slice(0,2)}</div><div><strong>{g.name}</strong><small>{g.active_mission_state?formatState(g.active_mission_state):formatState(g.availability)}</small></div><span className={g.freshness}>{g.freshness==='live'?'Live GPS':g.freshness}</span></article>)}{!workspace.guards.length&&!loading&&<Empty text="No Guards in this Agency roster."/>}</div></aside>
   <section className="aoc-mission-list"><div className="aoc-panel-head"><div><strong>{viewLabel(view).toUpperCase()}</strong><small>Mission Engine projection</small></div><span>{missions.length} missions</span></div>{missions.map(m=><article key={m.job_id} className={`aoc-mission ${m.priority} ${selected?.job_id===m.job_id?'selected':''}`} onClick={()=>setSelectedId(m.job_id)}><div className="aoc-mission-top"><span className={`aoc-priority ${m.priority}`}>{m.priority==='emergency'?<Siren/>:m.priority==='priority'?<Zap/>:<ShieldCheck/>}{m.priority}</span><b>{formatState(m.state)}</b></div><h3>{m.title}</h3><p><MapPin/>{m.property.address}</p><div className="aoc-progress"><i style={{width:`${progress(m)}%`}}/></div><footer><span>{m.guard?.name??'Unassigned'}</span><small>{m.state==='checkpoint'?`Checkpoint ${m.checkpoint_index}/${m.required_checkpoints}`:`${m.evidence_count} evidence · ${m.incident_count} incidents`}</small></footer></article>)}{!missions.length&&!loading&&<Empty text={`No missions in ${viewLabel(view).toLowerCase()}.`}/>}</section>
   <aside className="aoc-detail">{selected?<><div className="aoc-detail-hero">{selected.property.photo_url?<img src={selected.property.photo_url} alt={selected.property.name}/>:<div><MapPin/></div>}<span className={`aoc-priority ${selected.priority}`}>{selected.priority}</span></div><div className="aoc-detail-body"><small>MISSION AUTHORITY</small><h2>{selected.title}</h2><p>{selected.client.display_name}<br/>{selected.property.address}</p><div className="aoc-state-line"><strong>{formatState(selected.state)}</strong><span>Updated {relative(selected.updated_at)}</span></div><div className="aoc-detail-metrics"><span><Clock3/><b>{selected.duration_minutes} min</b><small>Duration</small></span><span><CheckCircle2/><b>{selected.checkpoint_index}/{selected.required_checkpoints}</b><small>Checkpoints</small></span><span><AlertTriangle/><b>{selected.incident_count}</b><small>Incidents</small></span></div>{selected.state==='awaiting_guard'?<div className="aoc-dispatch-box"><strong>Dispatch an available Guard</strong><select defaultValue="" disabled={assigning===selected.job_id} onChange={e=>{if(e.target.value)void assign(selected,e.target.value)}}><option value="" disabled>{assigning===selected.job_id?'Assigning…':'Select Guard'}</option>{available.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></div>:<div className="aoc-assigned"><UserRoundCheck/><div><small>ASSIGNED GUARD</small><strong>{selected.guard?.name??'Awaiting Guard response'}</strong></div></div>}</div></>:<Empty text="Select a mission to inspect its authoritative state."/>}</aside>
   <section className="aoc-feed"><div className="aoc-panel-head"><div><strong>OPERATIONS FEED</strong><small>Mission events, newest first</small></div><span><i className="live-dot"/>Realtime</span></div><div className="aoc-feed-grid">{workspace.events.slice(0,12).map(event=><article key={event.id}><span className={event.priority}>{eventIcon(event.event_type)}</span><time>{relative(event.created_at)}</time><div><strong>{humanEvent(event.event_type)}</strong><p>{event.title} · {event.property_name}</p></div></article>)}{!workspace.events.length&&!loading&&<Empty text="Mission events will appear here in real time."/>}</div></section>
  </div>
 </section>
}
function Metric({icon,label,value,detail,danger=false}:{icon:ReactNode;label:string;value:number;detail:string;danger?:boolean}){return <div className={`aoc-metric ${danger?'danger':''}`}><span>{icon}</span><div><small>{label}</small><strong>{value}</strong><p>{detail}</p></div></div>}
function Empty({text}:{text:string}){return <div className="aoc-empty"><Radio/><strong>{text}</strong></div>}
function formatState(value:string){return value.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function progress(m:OperationsMission){const map:Record<string,number>={awaiting_guard:5,offered:12,accepted:20,en_route:35,active:45,checkpoint:45+Math.round((m.checkpoint_index/Math.max(1,m.required_checkpoints))*40),review:92,completed:100,cancelled:0};return map[m.state]??0}
function relative(date:string){const seconds=Math.max(0,Math.floor((Date.now()-new Date(date).getTime())/1000));if(seconds<60)return 'just now';if(seconds<3600)return `${Math.floor(seconds/60)}m ago`;if(seconds<86400)return `${Math.floor(seconds/3600)}h ago`;return new Date(date).toLocaleDateString()}
function humanEvent(value:string){return formatState(value).replace('Rc21','').trim()}
function eventIcon(value:string){return value.includes('emergency')||value.includes('incident')?<Siren/>:value.includes('complete')?<CheckCircle2/>:value.includes('guard')?<Users/>:<Radio/>}
function viewLabel(view:View){return ({all:'Live Board',dispatch:'Dispatch Queue',active:'Missions in Motion',emergency:'Emergency Queue',completed:'Completed Missions'} as const)[view]}
function countFor(view:View,w:AgencyOperationsWorkspace){if(view==='all')return w.missions.filter(m=>m.state!=='cancelled').length;if(view==='dispatch')return w.missions.filter(m=>m.state==='awaiting_guard'||m.state==='offered').length;if(view==='active')return w.missions.filter(m=>['accepted','en_route','active','checkpoint','review'].includes(m.state)).length;if(view==='emergency')return w.missions.filter(m=>m.priority==='emergency'&&!['completed','cancelled'].includes(m.state)).length;return w.missions.filter(m=>m.state==='completed').length}
