import {useEffect,useMemo,useState} from 'react'
import {ChevronLeft,ChevronRight,FileText,RefreshCw,Search,ShieldCheck,X} from 'lucide-react'
import {getClientReports,subscribeToReports,type MissionReportRecord} from './modules/reporting/reportingRepository'
import {PublishedClientReport} from './ClientReports'
const key=(v:string|Date)=>{const d=new Date(v);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const label=(d:Date)=>d.toLocaleDateString(undefined,{month:'long',year:'numeric'})
export default function ClientReportsCalendar({preview=false}:{preview?:boolean}){
 const[reports,setReports]=useState<MissionReportRecord[]>([]),[loading,setLoading]=useState(!preview),[month,setMonth]=useState(()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth(),1)}),[day,setDay]=useState<string|null>(null),[all,setAll]=useState(false),[query,setQuery]=useState(''),[selected,setSelected]=useState<MissionReportRecord|null>(null)
 const load=async()=>{if(preview){setLoading(false);return}try{setReports((await getClientReports()).filter(r=>r.status==='published'))}finally{setLoading(false)}}
 useEffect(()=>{void load();if(preview)return;return subscribeToReports(()=>void load())},[preview])
 const byDay=useMemo(()=>reports.reduce<Record<string,MissionReportRecord[]>>((a,r)=>{(a[key(r.published_at||r.created_at)]??=[]).push(r);return a},{}),[reports])
 const cells=useMemo(()=>{const f=new Date(month.getFullYear(),month.getMonth(),1),s=new Date(f);s.setDate(1-f.getDay());return Array.from({length:42},(_,i)=>{const d=new Date(s);d.setDate(s.getDate()+i);return d})},[month])
 const recent=useMemo(()=>reports.filter(r=>Date.now()-new Date(r.published_at||r.created_at).getTime()<30*86400000),[reports])
 const rows=useMemo(()=>{let a=all?reports:day?(byDay[day]||[]):[];const q=query.trim().toLowerCase();return q?a.filter(r=>JSON.stringify(r.snapshot||{}).toLowerCase().includes(q)||r.id.toLowerCase().includes(q)):a},[all,day,reports,byDay,query])
 const close=()=>{setDay(null);setAll(false);setQuery('');setSelected(null)}
 if(loading)return <div className="client-loading"><RefreshCw/><h2>Loading reports</h2></div>
 return <section className="client-section client-report-calendar-system"><div className="client-section-head"><div><span>VERIFIED REPORT ARCHIVE</span><h2>Mission reports</h2><p>Choose a day to open published security records.</p></div></div>
 <div className="v4-report-summary"><button onClick={()=>setAll(true)}><span>Last 30 days</span><strong>{recent.length}</strong><small>Recent mission records</small></button><button onClick={()=>setAll(true)}><span>Published</span><strong>{reports.length}</strong><small>Verified reports</small></button><button onClick={()=>setAll(true)}><span>Properties</span><strong>{new Set(reports.map(r=>r.snapshot?.property?.name).filter(Boolean)).size}</strong><small>Protected locations</small></button><button onClick={()=>setAll(true)}><span>Report archive</span><strong>{reports.length}</strong><small>Search all records</small></button></div>
 <section className="v4-panel v4-calendar-panel"><div className="v4-calendar-head"><div><h3>Report calendar</h3><span>Published mission reports organized by date.</span></div><div className="v4-calendar-controls"><button className="v4-button" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}><ChevronLeft/></button><button className="v4-button" onClick={()=>{const d=new Date();setMonth(new Date(d.getFullYear(),d.getMonth(),1))}}>Today</button><strong>{label(month)}</strong><button className="v4-button" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><ChevronRight/></button></div></div><div className="v4-weekdays">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=><span key={x}>{x}</span>)}</div><div className="v4-calendar-grid">{cells.map(d=>{const k=key(d),r=byDay[k]||[];return <button key={k} disabled={!r.length} onClick={()=>{setDay(k);setAll(false)}} className={`${d.getMonth()===month.getMonth()?'':'muted'} ${r.length?'has-reports':''} ${k===key(new Date())?'today':''}`}><b>{d.getDate()}</b>{r.length?<div><strong>{r.length} report{r.length===1?'':'s'}</strong><small>Published</small></div>:null}</button>})}</div></section>
 {(day||all)&&<div className="v4-report-overlay client-report-center-overlay"><div className="v4-report-center"><header><div><small>CLIENT REPORT CENTER</small><h2>{day?new Date(day+'T12:00:00').toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'}):'Report archive'}</h2><span>{rows.length} verified report{rows.length===1?'':'s'}</span></div><button className="v4-button" onClick={close}><X/></button></header><div className="v4-report-center-body"><aside><label className="v4-report-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search property, agency, guard…"/></label><div className="v4-report-results">{rows.map(r=><button key={r.id} onClick={()=>setSelected(r)}><span className="v4-badge">Published</span><strong>{r.snapshot?.job?.title||'Completed mission'}</strong><small>{r.snapshot?.property?.name||'Property'} · {r.snapshot?.agency?.name||'Security agency'}</small><time>{new Date(r.published_at||r.created_at).toLocaleString()}</time></button>)}</div></aside><main><div className="v4-report-select"><ShieldCheck/><strong>Select a verified report</strong><span>The complete published mission record will open securely.</span></div></main></div></div></div>}
 {selected&&<PublishedClientReport report={selected} onClose={()=>setSelected(null)}/>}</section>
}
