import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import App from './app/App';
import { PortfolioProvider } from './store/PortfolioStore';
import { AgencyProvider } from './store/AgencyStore';
import { OutreachProvider } from './store/OutreachStore';
import { DistributionProvider } from './store/DistributionStore';
import './styles/index.css';
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><PortfolioProvider><AgencyProvider><OutreachProvider><DistributionProvider><App/></DistributionProvider></OutreachProvider></AgencyProvider></PortfolioProvider></BrowserRouter></React.StrictMode>);
