import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, Building2, CheckCircle2, Clock3, Radio, RefreshCw, ShieldCheck, Siren, Users, Wifi, Zap } from 'lucide-react'
import { useAuth } from './modules/auth/AuthProvider'
import { getPlatformMarketplace, subscribeToMarketplace, type MarketplaceJobRow, type MissionEventRow } from './modules/marketplace/marketplaceRepository'

export default function PlatformMissionControl(){
  const auth=useAuth();const {mode}=auth;const [jobs,setJobs]=useState<MarketplaceJobRow[]>([]);const [events,setEvents]=useState<MissionEventRow[]>([]);const [onlineGuards,setOnlineGuards]=useState(0);const [error,setError]=useState('');const [loading,setLoading]=useState(true)
  const load=async()=>{if(mode!=='supabase'){setLoading(false);return}try{const data=await getPlatformMarketplace();setJobs(data.jobs);setEvents(data.events);setOnlineGuards(data.onlineGuards);setError('')}catch(cause){setError(cause instanceof Error?cause.message:'Mission Control unavailable.')}finally{setLoading(false)}}
  useEffect(()=>{void load();if(mode!=='supabase')return;return subscribeToMarketplace(()=>void load())},[mode])
  const open=jobs.filter(j=>j.status==='open'),claimed=jobs.filter(j=>j.status==='accepted'),emergencies=jobs.filter(j=>j.priority==='emergency'&&!['completed','cancelled'].includes(j.status))
  const velocity=useMemo(()=>{if(jobs.length<2)return 'Awaiting activity';const times=jobs.map(j=>new Date(j.created_at).getTime()).sort((a,b)=>b-a);const mins=Math.max(1,Math.round((times[0]-times[Math.min(times.length-1,6)])/(Math.min(times.length-1,6)*60000)));return mins<60?`1 mission every ${mins} min`:`1 mission every ${Math.round(mins/60)} hr`},[jobs])
  if(loading)return <div className="auth-state"><div className="auth-state-card"><RefreshCw/><h1>Opening Mission Control</h1><p>Synchronizing the marketplace lifecycle…</p></div></div>
  return <div className="mission-control"><header><div><span><ShieldCheck/>CO PILOT</span><h1>Mission Control</h1><p>One live view of every marketplace state change.</p></div><div className="mc-header-actions"><div className={`mc-connection ${mode}`}><Wifi/>{mode==='supabase'?'LIVE':'PREVIEW'}</div></div></header>{error&&<div className="mc-error"><AlertTriangle/>{error}<button onClick={()=>void load()}>Retry</button></div>}<section className="mc-metrics"><Metric icon={<Radio/>} value={open.length} label="Open missions"/><Metric icon={<CheckCircle2/>} value={claimed.length} label="Claimed missions"/><Metric icon={<Users/>} value={onlineGuards} label="Online guards"/><Metric icon={<Siren/>} value={emergencies.length} label="Emergency layer"/></section><main><section className="mc-board"><div className="mc-section-head"><div><small>MARKETPLACE PULSE</small><h2>What is happening now</h2></div><span><Zap/>{velocity}</span></div><div className="mc-missions">{jobs.length?jobs.slice(0,12).map(job=><article key={job.id} className={`mc-mission ${job.priority}`}><div><span className={`mc-status ${job.status}`}>{job.status}</span><small>{new Date(job.created_at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</small></div>{job.property?.photo_url&&<img className="mc-property-photo" src={job.property.photo_url} alt=""/>}<h3>{job.title}</h3><p><Building2/>{job.property?.name||'Verified property'}</p><footer><span>{job.priority.toUpperCase()}</span><b>#{job.id.slice(0,8).toUpperCase()}</b></footer></article>):<div className="mc-empty">No marketplace missions yet.</div>}</div></section><aside className="mc-feed"><div className="mc-section-head"><div><small>MISSION FEED</small><h2>Timeline is truth</h2></div></div>{events.length?events.map(event=><div className="mc-event" key={event.id}><span><Clock3/></span><div><strong>{event.event_type.replaceAll('_',' ')}</strong><small>Mission #{event.job_id.slice(0,8).toUpperCase()}</small><time>{new Date(event.created_at).toLocaleString()}</time></div></div>):<div className="mc-empty">Events will appear as missions move.</div>}</aside></main><div className="build-badge">RC1 · FOUNDATION LOCK</div></div>
}
function Metric({icon,value,label}:{icon:React.ReactNode;value:number;label:string}){return <article><span>{icon}</span><div><strong>{value}</strong><small>{label}</small></div></article>}
