import { useEffect,useMemo,useState } from 'react'
import { Activity,AlertTriangle,CheckCircle2,Clock3,MapPin,Navigation,Radio,RefreshCw,ShieldCheck,Siren,Users,Wifi,Zap } from 'lucide-react'
import { useAuth } from './modules/auth/AuthProvider'
import { getLiveOperationsCenter,subscribeToLiveOperations,type LiveOperationsSnapshot } from './modules/platform/liveOperationsRepository'

type View='operations'|'missions'|'guards'|'health'
const empty={marketplace_open:0,missions_live:0,guards_online:0,guards_available:0,guards_driving:0,completed_today:0,reports_pending:0,reports_published:0,emergencies_live:0,priority_live:0}
export default function PlatformMissionControl(){
 const {mode}=useAuth();const[view,setView]=useState<View>('operations');const[data,setData]=useState<LiveOperationsSnapshot|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('')
 const load=async()=>{if(mode!=='supabase'){setLoading(false);return}try{setData(await getLiveOperationsCenter());setError('')}catch(e){setError(e instanceof Error?e.message:'Live Operations unavailable')}finally{setLoading(false)}}
 useEffect(()=>{void load();if(mode!=='supabase')return;return subscribeToLiveOperations(()=>void load())},[mode])
 const s=data?.summary??empty;const liveMissions=useMemo(()=>data?.missions.filter(m=>!['completed','cancelled'].includes(m.status)).slice(0,12)??[],[data]);const events=data?.events.slice(0,24)??[]
 if(loading)return <div className="auth-state"><div className="auth-state-card"><RefreshCw/><h1>Opening Live Operations</h1><p>Synchronizing platform engines…</p></div></div>
 return <div className="platform-command-center live-operations-center">
  <header className="pcc-header"><div><span><ShieldCheck/>CO PILOT SECURITY OS</span><h1>Live Operations</h1><p>One realtime view of marketplace, missions, guards, reports, and engine health.</p></div><div className="mc-connection supabase"><Wifi/>LIVE</div></header>
  <nav className="pcc-nav">{(['operations','missions','guards','health'] as View[]).map(x=><button key={x} className={view===x?'active':''} onClick={()=>setView(x)}>{x[0].toUpperCase()+x.slice(1)}</button>)}</nav>
  {error&&<div className="mc-error"><AlertTriangle/>{error}<button onClick={()=>void load()}>Retry</button></div>}
  {view==='operations'&&<>
   <section className="pcc-metrics live-kpis"><Metric icon={<Radio/>} value={s.missions_live} label="Live missions"/><Metric icon={<Users/>} value={s.guards_online} label="Online guards"/><Metric icon={<Navigation/>} value={s.guards_driving} label="Driving"/><Metric icon={<Siren/>} value={s.emergencies_live} label="Emergencies"/></section>
   <section className="pcc-system-strip live-strip"><span><b>{s.marketplace_open}</b>Marketplace</span><span><b>{s.guards_available}</b>Available</span><span><b>{s.completed_today}</b>Completed today</span><span><b>{s.reports_pending}</b>Reports pending</span><span><b>{s.reports_published}</b>Published</span></section>
   <main className="pcc-command-grid"><section className="pcc-panel"><Head eyebrow="LIVE MISSION PIPELINE" title="What is happening now"/><div className="live-pipeline">{liveMissions.map(m=><article key={m.id}><div className="live-pipeline-state"><span className={`pcc-status ${m.engine_state??m.status}`}>{(m.engine_state??m.status).replaceAll('_',' ')}</span><time>{new Date(m.updated_at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</time></div><h3>{m.title}</h3><p><MapPin/>{m.property_name} · {m.property_address}</p><div className="live-pipeline-route"><span>{m.client_name}</span><i>→</i><span>{m.agency_name??'Marketplace'}</span><i>→</i><span>{m.guard_name??'No guard'}</span></div>{m.checkpoint_index?<small>Checkpoint {m.checkpoint_index} of 6</small>:null}</article>)}</div></section>
   <aside className="pcc-panel"><Head eyebrow="GLOBAL EVENT FEED" title="Every engine transition"/><div className="pcc-event-feed">{events.map(e=><article key={e.id}><span><Clock3/></span><div><strong>{e.event_type.replaceAll('_',' ')}</strong><p>{e.mission_title}</p><small>{e.actor_name} · {new Date(e.created_at).toLocaleString()}</small></div></article>)}</div></aside></main>
  </>}
  {view==='missions'&&<section className="pcc-page"><Head eyebrow="MISSION ENGINE" title="End-to-end operational state"/><div className="pcc-table"><div className="pcc-table-head"><span>Mission</span><span>Property</span><span>Ownership</span><span>State</span></div>{data?.missions.map(m=><div className="pcc-table-row" key={m.id}><span><b>{m.title}</b><small>{m.priority}</small></span><span><b>{m.property_name}</b><small>{m.property_address}</small></span><span><b>{m.agency_name??'Marketplace'}</b><small>{m.guard_name??'No guard'}</small></span><span><i className={`pcc-status ${m.engine_state??m.status}`}>{(m.engine_state??m.status).replaceAll('_',' ')}</i><small>{m.report_status?`Report: ${m.report_status.replaceAll('_',' ')}`:'No report yet'}</small></span></div>)}</div></section>}
  {view==='guards'&&<section className="pcc-page"><Head eyebrow="LIVE LOCATION READINESS" title={`${s.guards_online} guards online`}/><div className="pcc-card-grid">{data?.guards.map(g=><article className="pcc-entity-card" key={g.id}><div className="pcc-avatar">{g.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div><span className={`pcc-status ${g.availability}`}>{g.availability.replaceAll('_',' ')}</span><h3>{g.name}</h3><p>{g.agency_name}</p><small className={`location-freshness ${g.location_freshness}`}>{g.latitude!=null&&g.longitude!=null?`${g.location_freshness.toUpperCase()} · ${g.latitude.toFixed(4)}, ${g.longitude.toFixed(4)}`:'Awaiting first GPS signal'}</small></div></article>)}</div></section>}
  {view==='health'&&<section className="pcc-page"><Head eyebrow="ENGINE HEALTH" title="Platform readiness"/><div className="engine-health-grid">{data&&Object.entries(data.health).map(([name,status])=><article key={name} className={`engine-health-card ${status}`}><span>{status==='healthy'||status==='connected'||status==='receiving'?<CheckCircle2/>:<Activity/>}</span><div><h3>{name.replaceAll('_',' ')}</h3><p>{status.replaceAll('_',' ')}</p></div></article>)}</div></section>}
  <div className="build-badge">LIVE OPERATIONS ENGINE · ACCEPTANCE BUILD</div>
 </div>
}
function Metric({icon,value,label}:{icon:React.ReactNode;value:number;label:string}){return <article><span>{icon}</span><div><strong>{value}</strong><small>{label}</small></div></article>}
function Head({eyebrow,title}:{eyebrow:string;title:string}){return <div className="pcc-panel-head"><div><small>{eyebrow}</small><h2>{title}</h2></div><Zap/></div>}
