import { useEffect,useState } from 'react'
import { AlertTriangle,CheckCircle2,ChevronRight,Clock3,FileText,Image,MapPin,Printer,RefreshCw,Send,ShieldCheck,X } from 'lucide-react'
import { getAgencyReports,reviewMissionReport,subscribeToReports,type MissionReportRecord } from './modules/reporting/reportingRepository'
export default function ReportingWorkspace({preview=false,onCount}:{preview?:boolean;onCount?:(n:number)=>void}){
 const[reports,setReports]=useState<MissionReportRecord[]>([]),[selected,setSelected]=useState<MissionReportRecord|null>(null),[loading,setLoading]=useState(!preview),[error,setError]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false)
 const load=async()=>{if(preview){setLoading(false);return}try{const rows=await getAgencyReports();setReports(rows);onCount?.(rows.filter(r=>r.status==='pending_review').length);if(selected)setSelected(rows.find(r=>r.id===selected.id)??null);setError('')}catch(e){setError(e instanceof Error?e.message:'Reports unavailable')}finally{setLoading(false)}}
 useEffect(()=>{void load();if(preview)return;return subscribeToReports(()=>void load())},[preview])
 const act=async(action:'publish'|'clarification')=>{if(!selected)return;setBusy(true);try{await reviewMissionReport(selected.id,action,note);setNote('');await load()}catch(e){setError(e instanceof Error?e.message:'Report action failed')}finally{setBusy(false)}}
 if(loading)return <div className="reporting-state"><RefreshCw/><h2>Opening Reporting Engine</h2></div>
 return <section className="reporting-workspace"><header><div><small>REPORTING ENGINE</small><h1>Mission Reports</h1><p>Review immutable mission records before client publication.</p></div><span>{reports.filter(r=>r.status==='pending_review').length} pending</span></header>{error&&<div className="reporting-error"><AlertTriangle/>{error}</div>}<div className="reporting-layout"><div className="reporting-list">{reports.length?reports.map(r=>{const s=r.snapshot;return <button key={r.id} className={selected?.id===r.id?'active':''} onClick={()=>{setSelected(r);setNote(r.agency_review_note??'')}}><span className={`report-status ${r.status}`}>{r.status.replaceAll('_',' ')}</span><h3>{s?.job?.title??'Completed mission'}</h3><p><MapPin/>{s?.property?.name} · {s?.property?.address}</p><footer><span>{s?.guard?.name??'Guard'}</span><time>{new Date(r.created_at).toLocaleString()}</time><ChevronRight/></footer></button>}):<div className="reporting-empty"><FileText/><h3>No completed mission reports</h3><p>A report is created automatically when the Mission Engine completes a patrol.</p></div>}</div>{selected&&<ReportDetail report={selected} note={note} setNote={setNote} busy={busy} publish={()=>void act('publish')} clarify={()=>void act('clarification')} close={()=>setSelected(null)}/>}</div></section>
}
function ReportDetail({report,note,setNote,busy,publish,clarify,close}:{report:MissionReportRecord;note:string;setNote:(v:string)=>void;busy:boolean;publish:()=>void;clarify:()=>void;close:()=>void}){const s=report.snapshot,m=s?.mission??{},e=Array.isArray(m.evidence)?m.evidence:[],timeline=Array.isArray(s?.timeline)?s.timeline:[];return <article className="report-detail"><header><div><small>REPORT v{report.version}.0</small><h2>{s?.job?.title}</h2><p>{s?.property?.name} · {s?.property?.address}</p></div><button onClick={close}><X/></button></header><div className="report-detail-metrics"><span><Clock3/><b>{m.completed_at?new Date(m.completed_at).toLocaleString():'Completed'}</b><small>Completion</small></span><span><ShieldCheck/><b>{s?.guard?.name}</b><small>Guard</small></span><span><CheckCircle2/><b>6 of 6</b><small>Checkpoints</small></span><span><Image/><b>{e.reduce((n:number,x:any)=>n+(x.photos||0)+(x.videos||0)+(x.note?1:0),0)}</b><small>Evidence</small></span></div><section><h3>Checkpoint record</h3><div className="report-checkpoints">{['Exterior Perimeter','Parking Lot','Main Entrance','Back Entrance','Rear Loading Dock','Side Doors'].map((name,i)=>{const x=e.find((v:any)=>v.checkpoint===i);return <div key={name}><CheckCircle2/><span><b>{name}</b><small>{x?`${x.photos||0} photos · ${x.videos||0} videos${x.note?' · note':''}`:'Completed · no evidence'}</small></span></div>})}</div></section><section><h3>Mission timeline</h3><div className="report-engine-timeline">{timeline.map((x:any)=><div key={x.id}><i/><span><b>{String(x.event_type).replaceAll('_',' ')}</b><small>{new Date(x.created_at).toLocaleString()} · {x.actor_name??'System'}</small></span></div>)}</div></section><section><h3>Agency review</h3><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Optional client-facing review note" disabled={report.status==='published'}/>{report.status!=='published'?<div className="report-actions"><button onClick={clarify} disabled={busy||!note.trim()}><AlertTriangle/>Return for clarification</button><button className="primary" onClick={publish} disabled={busy}><Send/>Publish to Client</button></div>:<div className="report-published"><CheckCircle2/>Published to Client {report.published_at&&new Date(report.published_at).toLocaleString()}<button onClick={()=>window.print()}><Printer/>Print / Save PDF</button></div>}</section></article>}
