-- V1 request-mode pricing. Superseded function definitions are fully captured in 202610060002_vacation_watch_packages_v1.sql.
-- Scheduled unarmed $40/hr; Now unarmed $50/hr; Scheduled armed $55/hr; Now armed $70/hr.
-- Vacation Watch is $35/visit with $25 agency payout and $10 platform fee.
