alter table public.guards add column if not exists avatar_url text, add column if not exists phone text, add column if not exists emergency_contact_name text, add column if not exists emergency_contact_phone text, add column if not exists preferred_shift text not null default 'any' check (preferred_shift in ('any','day','evening','overnight')), add column if not exists max_travel_miles integer not null default 25 check (max_travel_miles between 1 and 250), add column if not exists notification_preferences jsonb not null default '{"assignment_alerts":true,"agency_messages":true,"schedule_reminders":true,"credential_reminders":true}'::jsonb, add column if not exists updated_at timestamptz not null default now();
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('guard-avatars','guard-avatars',true,5242880,array['image/jpeg','image/png','image/webp']) on conflict(id) do update set public=true,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy guard_avatars_read on storage.objects for select using(bucket_id='guard-avatars');
create policy guard_avatars_insert_own on storage.objects for insert to authenticated with check(bucket_id='guard-avatars' and split_part(name,'/',1)=auth.uid()::text);
create policy guard_avatars_update_own on storage.objects for update to authenticated using(bucket_id='guard-avatars' and split_part(name,'/',1)=auth.uid()::text) with check(bucket_id='guard-avatars' and split_part(name,'/',1)=auth.uid()::text);
create policy guard_avatars_delete_own on storage.objects for delete to authenticated using(bucket_id='guard-avatars' and split_part(name,'/',1)=auth.uid()::text);
create or replace function public.get_my_guard_settings_rc1() returns jsonb language plpgsql security definer set search_path=public as $$ declare g public.guards; p public.profiles; begin select * into g from public.guards where user_id=auth.uid(); if g.id is null then raise exception 'GUARD_PROFILE_NOT_FOUND'; end if; select * into p from public.profiles where id=auth.uid(); return jsonb_build_object('id',g.id,'user_id',g.user_id,'agency_id',g.agency_id,'name',coalesce(p.full_name,p.email,'Guard'),'email',p.email,'avatar_url',g.avatar_url,'phone',g.phone,'badge_number',g.badge_number,'availability',g.availability,'emergency_contact_name',g.emergency_contact_name,'emergency_contact_phone',g.emergency_contact_phone,'preferred_shift',g.preferred_shift,'max_travel_miles',g.max_travel_miles,'notification_preferences',g.notification_preferences); end $$;
create or replace function public.update_my_guard_settings_rc1(p_avatar_url text,p_phone text,p_emergency_contact_name text,p_emergency_contact_phone text,p_preferred_shift text,p_max_travel_miles integer,p_notification_preferences jsonb) returns jsonb language plpgsql security definer set search_path=public as $$ begin if p_preferred_shift not in ('any','day','evening','overnight') then raise exception 'INVALID_SHIFT'; end if; if p_max_travel_miles not between 1 and 250 then raise exception 'INVALID_TRAVEL_RADIUS'; end if; update public.guards set avatar_url=nullif(trim(p_avatar_url),''),phone=nullif(trim(p_phone),''),emergency_contact_name=nullif(trim(p_emergency_contact_name),''),emergency_contact_phone=nullif(trim(p_emergency_contact_phone),''),preferred_shift=p_preferred_shift,max_travel_miles=p_max_travel_miles,notification_preferences=coalesce(p_notification_preferences,'{}'::jsonb),updated_at=now() where user_id=auth.uid(); if not found then raise exception 'GUARD_PROFILE_NOT_FOUND'; end if; return public.get_my_guard_settings_rc1(); end $$;
grant execute on function public.get_my_guard_settings_rc1() to authenticated; grant execute on function public.update_my_guard_settings_rc1(text,text,text,text,text,integer,jsonb) to authenticated;
