-- Guard-controlled display name plus avatar propagation in admin live-account test.
create or replace function public.update_my_guard_settings_rc1(p_name text,p_avatar_url text,p_phone text,p_emergency_contact_name text,p_emergency_contact_phone text,p_preferred_shift text,p_max_travel_miles integer,p_notification_preferences jsonb) returns jsonb language plpgsql security definer set search_path=public as $$ begin if length(trim(coalesce(p_name,'')))<2 then raise exception 'INVALID_GUARD_NAME'; end if; if p_preferred_shift not in ('any','day','evening','overnight') then raise exception 'INVALID_SHIFT'; end if; if p_max_travel_miles not between 1 and 250 then raise exception 'INVALID_TRAVEL_RADIUS'; end if; update public.profiles set full_name=trim(p_name),updated_at=now() where id=auth.uid(); update public.guards set avatar_url=nullif(trim(p_avatar_url),''),phone=nullif(trim(p_phone),''),emergency_contact_name=nullif(trim(p_emergency_contact_name),''),emergency_contact_phone=nullif(trim(p_emergency_contact_phone),''),preferred_shift=p_preferred_shift,max_travel_miles=p_max_travel_miles,notification_preferences=coalesce(p_notification_preferences,'{}'::jsonb),updated_at=now() where user_id=auth.uid(); if not found then raise exception 'GUARD_PROFILE_NOT_FOUND'; end if; return public.get_my_guard_settings_rc1(); end $$;
grant execute on function public.update_my_guard_settings_rc1(text,text,text,text,text,text,integer,jsonb) to authenticated;

create or replace function public.update_developer_guard_settings_rc1(p_guard_id uuid,p_name text,p_avatar_url text,p_phone text,p_emergency_contact_name text,p_emergency_contact_phone text,p_preferred_shift text,p_max_travel_miles integer,p_notification_preferences jsonb) returns jsonb language plpgsql security definer set search_path=public set row_security=off as $$ declare v_user uuid; begin if not exists(select 1 from public.profiles where id=auth.uid() and role='platform_admin') then raise exception 'PLATFORM_ADMIN_REQUIRED'; end if; if length(trim(coalesce(p_name,'')))<2 then raise exception 'INVALID_GUARD_NAME'; end if; if p_preferred_shift not in ('any','day','evening','overnight') then raise exception 'INVALID_SHIFT'; end if; if p_max_travel_miles not between 1 and 250 then raise exception 'INVALID_TRAVEL_RADIUS'; end if; select user_id into v_user from public.guards where id=p_guard_id; if v_user is null then raise exception 'GUARD_PROFILE_NOT_FOUND'; end if; update public.profiles set full_name=trim(p_name),updated_at=now() where id=v_user; update public.guards set avatar_url=nullif(trim(p_avatar_url),''),phone=nullif(trim(p_phone),''),emergency_contact_name=nullif(trim(p_emergency_contact_name),''),emergency_contact_phone=nullif(trim(p_emergency_contact_phone),''),preferred_shift=p_preferred_shift,max_travel_miles=p_max_travel_miles,notification_preferences=coalesce(p_notification_preferences,'{}'::jsonb),updated_at=now() where id=p_guard_id; return public.get_developer_guard_settings_rc1(p_guard_id); end $$;
grant execute on function public.update_developer_guard_settings_rc1(uuid,text,text,text,text,text,text,integer,jsonb) to authenticated;

create or replace function public.get_developer_agency_workspace_rc2(p_agency_id uuid) returns jsonb language plpgsql security definer set search_path=public set row_security=off as $$ declare a public.agencies; begin if not exists(select 1 from public.profiles where id=auth.uid() and role='platform_admin') then raise exception 'PLATFORM_ADMIN_REQUIRED'; end if; select * into a from public.agencies where id=p_agency_id; if a.id is null then raise exception 'AGENCY_NOT_FOUND'; end if; return jsonb_build_object('agency',jsonb_build_object('id',a.id,'name',a.name,'status',a.status),'guards',(select coalesce(jsonb_agg(jsonb_build_object('id',g.id,'user_id',g.user_id,'agency_id',g.agency_id,'name',coalesce(p.full_name,'Guard'),'availability',g.availability,'avatar_url',g.avatar_url,'latitude',g.latitude,'longitude',g.longitude,'last_location_at',g.last_location_at) order by p.full_name),'[]') from public.guards g left join public.profiles p on p.id=g.user_id where g.agency_id=p_agency_id),'jobs',(select coalesce(jsonb_agg(to_jsonb(j)),'[]') from public.jobs j where j.accepted_agency_id=p_agency_id or j.status='open')); end $$;
grant execute on function public.get_developer_agency_workspace_rc2(uuid) to authenticated;
