-- RC1.3 Guard Presence Engine
-- Database authority for Guard online/offline transitions and Agency synchronization.
begin;

create table if not exists public.guard_presence_events (
  id bigint generated by default as identity primary key,
  guard_id uuid not null references public.guards(id) on delete cascade,
  agency_id uuid not null references public.agencies(id) on delete cascade,
  actor_user_id uuid not null references auth.users(id) on delete cascade,
  previous_availability text not null,
  next_availability text not null,
  created_at timestamptz not null default now(),
  constraint guard_presence_events_previous_check check (previous_availability in ('offline','available','reserved','on_mission')),
  constraint guard_presence_events_next_check check (next_availability in ('offline','available','reserved','on_mission'))
);

create index if not exists guard_presence_events_guard_created_idx
  on public.guard_presence_events(guard_id, created_at desc);

alter table public.guard_presence_events enable row level security;

create or replace function public.set_guard_presence_rc13(p_online boolean)
returns jsonb
language plpgsql
security definer
set search_path=public
set row_security=off
as $$
declare
  v_guard public.guards;
  v_previous text;
  v_next text;
begin
  select * into v_guard
  from public.guards
  where user_id=auth.uid()
  for update;

  if v_guard.id is null then
    raise exception 'GUARD_PROFILE_NOT_FOUND' using errcode='42501';
  end if;

  v_previous := v_guard.availability;

  if p_online then
    if v_previous='offline' then
      v_next := 'available';
    else
      v_next := v_previous;
    end if;
  else
    if v_previous='available' then
      v_next := 'offline';
    elsif v_previous='offline' then
      v_next := 'offline';
    else
      raise exception 'GUARD_CANNOT_GO_OFFLINE_WHILE_%', upper(v_previous) using errcode='22023';
    end if;
  end if;

  if v_next is distinct from v_previous then
    update public.guards
      set availability=v_next
    where id=v_guard.id;

    insert into public.guard_presence_events(
      guard_id,agency_id,actor_user_id,previous_availability,next_availability
    ) values (
      v_guard.id,v_guard.agency_id,auth.uid(),v_previous,v_next
    );
  end if;

  return jsonb_build_object(
    'success',true,
    'guard_id',v_guard.id,
    'agency_id',v_guard.agency_id,
    'availability',v_next,
    'online',v_next<>'offline',
    'changed',v_next is distinct from v_previous
  );
end;
$$;

create or replace function public.get_guard_presence_rc13()
returns jsonb
language plpgsql
security definer
set search_path=public
set row_security=off
as $$
declare
  v_guard public.guards;
begin
  select * into v_guard from public.guards where user_id=auth.uid();
  if v_guard.id is null then
    raise exception 'GUARD_PROFILE_NOT_FOUND' using errcode='42501';
  end if;
  return jsonb_build_object(
    'guard_id',v_guard.id,
    'agency_id',v_guard.agency_id,
    'availability',v_guard.availability,
    'online',v_guard.availability<>'offline'
  );
end;
$$;

revoke all on function public.set_guard_presence_rc13(boolean) from public;
revoke all on function public.get_guard_presence_rc13() from public;
grant execute on function public.set_guard_presence_rc13(boolean) to authenticated;
grant execute on function public.get_guard_presence_rc13() to authenticated;

-- Ensure Guard changes are eligible for Supabase Realtime. Ignore duplicate membership.
do $$
begin
  alter publication supabase_realtime add table public.guards;
exception
  when duplicate_object then null;
  when undefined_object then null;
end $$;

commit;
